import type { ModuleContent } from "./module-types";

export const atexModuleContent: ModuleContent = {
  title: "Formation et Sensibilisation ATEX NIV 0",
  shortTitle: "ATEX NIV 0",
  subtitle:
    "Parcours e-learning de sensibilisation aux atmosphères explosives, destiné à toute personne amenée à travailler, intervenir ou évoluer dans un environnement susceptible de présenter un risque d'explosion lié à des gaz, vapeurs ou poussières inflammables.",
  duration: "2 h + entretien 30 min",
  deliveryFormat: "E-learning autonome 2h + entretien de validation 30 min",
  level: "Débutant à intermédiaire",
  objective:
    "Comprendre ce qu'est une atmosphère explosive, identifier les zones ATEX (gaz et poussières), connaître le mécanisme d'une explosion et ses 6 conditions, appliquer les mesures de prévention adaptées, utiliser les EPI appropriés et respecter la signalisation réglementaire en zone ATEX.",
  audience:
    "Tout personnel amené à intervenir, travailler ou circuler dans un environnement pouvant présenter un risque ATEX : industrie chimique, pétrochimique, agroalimentaire (farine, sucre, amidon), traitement des eaux, imprimerie, menuiserie, métallurgie, stockage de produits inflammables.",
  certificationNote:
    "Ce parcours constitue une sensibilisation théorique conforme à la directive 99/92/CE, à l'arrêté du 8 juillet 2003 et aux articles R.4227-42 à R.4227-54 du Code du travail. Son contenu est élaboré en référence au Guide ISM-ATEX de l'INERIS. À l'issue du e-learning, un entretien individuel de 30 minutes avec un formateur PREVENSIA permet de vérifier la compréhension des objectifs et de délivrer l'attestation de sensibilisation ATEX NIV 0. La classification des zones, le choix des équipements et les procédures spécifiques restent de la responsabilité de l'employeur.",
  heroBadge: "ATEX NIV 0",
  finalMessage:
    "En zone ATEX, chaque intervenant est un maillon de la prévention. Respecter les procédures, signaler toute anomalie, ne jamais utiliser un outil ou un équipement non adapté à la zone : ces réflexes simples évitent les accidents graves. La formation théorique doit être complétée par une sensibilisation terrain encadrée par l'employeur.",
  quizCtaLabel: "Passer au quiz ATEX NIV 0",
  sections: [
    {
      id: "introduction-atex",
      title: "1. Qu'est-ce qu'une atmosphère explosive ?",
      estimatedMinutes: 15,
      chapterImagePath: "/elearning/atex/atex-formation-lie-lse.png",
      chapterImageAlt: "Formation d'une ATEX — triangle du feu, domaine d'explosivité LIE/LSE",
      intro:
        "Une atmosphère explosive (ATEX) est un mélange d'air et de substances inflammables sous forme de gaz, vapeurs ou poussières. Lorsqu'elle s'enflamme, la réaction peut provoquer une explosion aux conséquences dévastatrices. Comprendre ce mécanisme est la première ligne de défense.",
      content: [
        "Une atmosphère explosive (ATEX) se forme lorsque des substances combustibles — gaz, vapeurs, brouillards ou poussières — se mélangent à l'air dans des proportions situées entre la Limite Inférieure d'Explosivité (LIE) et la Limite Supérieure d'Explosivité (LSE). En-dessous de la LIE, le mélange est trop pauvre ; au-dessus de la LSE, il est trop riche. Seule la plage entre ces deux valeurs est explosive. Le guide INERIS Oméga 36 (octobre 2025) distingue « atmosphère explosive » (mélange dans son domaine d'explosivité) et « atmosphère explosible » (susceptible de le devenir par évolution des concentrations).",
        "Les ATEX sont présentes dans de nombreux secteurs professionnels : industrie chimique et pétrochimique, industries agroalimentaires (silos de farine, de sucre, d'amidon), traitement des eaux et du gaz, imprimerie, menuiserie fine, métallurgie, stations-service et dépôts de carburant.",
        "Les accidents liés aux ATEX provoquent chaque année en France des dizaines d'accidents du travail graves. Les explosions surviennent principalement en usine/atelier (43 AT recensés), lors d'opérations de maintenance ou de réparation (17 AT), et sur chantiers de construction (15 AT).",
        "La prévention des risques ATEX repose sur trois piliers : supprimer ou réduire la formation d'atmosphères explosives, éviter toute source d'inflammation, et mettre en place des mesures atténuant les effets d'une explosion éventuelle.",
        "Le Code du travail (articles L4121-1 et suivants) impose à l'employeur d'évaluer les risques liés aux atmosphères explosives et de prendre les mesures nécessaires pour assurer la sécurité des travailleurs exposés.",
      ],
      deepDive: [
        "La directive européenne 99/92/CE (directive ATEX « lieux de travail ») a été transposée en droit français par le décret du 19 novembre 2002 (décret 2002-1553). Elle définit les prescriptions minimales visant à améliorer la protection en matière de sécurité et de santé des travailleurs susceptibles d'être exposés aux risques découlant des atmosphères explosives.",
        "La directive 2014/34/UE (refonte de la directive 94/9/CE, dite ATEX 95 ou ATEX équipements) encadre pour sa part la mise sur le marché des appareils et systèmes de protection utilisés dans les atmosphères explosives. Ces deux directives sont complémentaires et forment le cadre réglementaire ATEX.",
        "L'employeur est tenu d'établir un Document Relatif à la Protection Contre les Explosions (DRPCE) précisant les risques identifiés, la classification des zones, les mesures de prévention et les équipements utilisés.",
      ],
      keyPoints: [
        "ATEX = mélange air + substances inflammables (gaz, vapeurs, poussières) en proportions explosibles.",
        "Présentes dans de nombreux secteurs industriels, y compris agroalimentaire et traitement des eaux.",
        "La directive 99/92/CE impose des obligations à l'employeur.",
        "L'employeur doit établir un Document Relatif à la Protection Contre les Explosions (DRPCE).",
        "Trois piliers : supprimer l'atmosphère, éviter l'inflammation, atténuer les effets.",
      ],
      legalRefs: [
        "Code du travail - Art. L4121-1 à L4121-5 : obligation générale de prévention.",
        "Directive 99/92/CE transposée par décret 2002-1553 : prescriptions minimales pour les lieux de travail ATEX.",
        "Directive 2014/34/UE (ATEX équipements, refonte 94/9/CE) : appareils et systèmes de protection utilisés en zone ATEX.",
        "Art. R4227-42 et suivants du Code du travail : dispositions spécifiques aux atmosphères explosives.",
      ],
    },
    {
      id: "statistiques-reglementation",
      title: "2. La réglementation ATEX",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-exemple-marquage-label.png",
      chapterImageAlt: "Exemple de marquage ATEX : II 2G Ex ib IIC T4 Gb / II 2D Ex ib IIIC T135°C Db IP64",
      intro:
        "Deux directives européennes constituent le socle de la réglementation ATEX. L'une concerne les employeurs, l'autre les fabricants d'équipements. Les connaître est indispensable pour agir conformément à la loi.",
      content: [
        "La directive 99/92/CE (dite ATEX 137 ou ATEX lieux de travail) fixe les responsabilités de l'employeur. Elle impose d'évaluer les risques d'explosion sur le site, de classer les zones à risques et de les signaliser, de tenir un Document Relatif à la Protection Contre les Explosions (DRPCE), de mettre en œuvre des mesures techniques et organisationnelles de prévention, et de respecter les critères de sélection des appareils selon la zone.",
        "La directive 2014/34/UE (refonte de la directive 94/9/CE, dite ATEX 95 ou ATEX équipements) concerne les fabricants d'équipements. Elle définit les exigences en matière d'équipements et de systèmes de protection destinés aux atmosphères explosives (détecteurs de gaz, moteurs, coffrets), les exigences pour les dispositifs de commande et de contrôle utilisés hors zone ATEX mais nécessaires au bon fonctionnement des équipements, ainsi que la classification des groupes d'équipements en catégories et les exigences essentielles de conception et fabrication.",
        "Pour être conforme à la directive ATEX, un équipement doit : porter le marquage CE, disposer des certifications nécessaires pour les zones dangereuses, répondre à une norme reconnue (exemple : EN 60079-29-1 pour les détecteurs de gaz inflammables), et porter le marquage Ex avec l'indication du groupe, de la catégorie, du mode de protection et de la classe de température.",
        "Le marquage réglementaire ATEX permet d'identifier la compatibilité d'un équipement avec les zones. Il se décompose en : groupe d'appareils (II pour surfaces, I pour mines), catégorie (1G/2G/3G pour gaz, 1D/2D/3D pour poussières), mode de protection Ex (d, e, ia, ib, p, n...), groupe de gaz (IIA, IIB, IIC), et classe de température (T1 à T6). Pour les poussières, la température maximale de surface est indiquée directement.",
        "Les gaz et vapeurs sont classés en trois familles selon leur sensibilité à l'inflammation : IIA (propane - moins dangereux), IIB (éthylène), IIC (hydrogène et acétylène - le plus dangereux). Les poussières sont classées selon leur état de division et leur conductivité. L'organisme IECEx (Commission Electrotechnique Internationale) émet des normes équivalentes utilisées hors Europe, que l'on retrouve souvent sur les fiches techniques des équipements.",
        "L'employeur doit procéder à une évaluation des risques d'explosion prenant en compte : la probabilité de formation d'une atmosphère explosive (qui détermine la classification des zones), la probabilité de présence d'une source d'inflammation (qui détermine la catégorie d'équipement requise), et la nature des matériaux inflammables (groupes de gaz, température d'inflammation, indice T).",
      ],
      deepDive: [
        "Exemples de formation d'une ATEX selon l'INERIS : une ATEX de type zone 2 se forme dans l'air ambiant à proximité d'une flaque d'un liquide à point d'éclair inférieur à l'ambiante répandu accidentellement. De même, une canalisation sous pression d'un gaz inflammable présentant une fuite (dysfonctionnement) crée une zone 2 dans son environnement immédiat.",
        "Le DRPCE (Document Relatif à la Protection Contre les Explosions) doit être établi avant le début des travaux et tenu à jour. Il reprend : l'identification des zones ATEX, les mesures de prévention mises en place, la liste des équipements certifiés utilisés dans chaque zone et les procédures spécifiques aux interventions en zone.",
        "Le signe CE + Ex sur un équipement autorise sa libre circulation dans l'Union Européenne. Ce marquage atteste que l'équipement a été conçu, testé et certifié pour ne pas constituer une source d'inflammation dans les conditions d'utilisation prévues.",
      ],
      keyPoints: [
        "Directive 99/92/CE (ATEX 137) = obligations de l'EMPLOYEUR.",
        "Directive 2014/34/UE (ATEX 95) = obligations du FABRICANT d'équipements.",
        "DRPCE obligatoire : document à établir avant tout travail, à tenir à jour.",
        "Marquage Ex = certification équipement : groupe + catégorie + mode protection + classe température.",
        "Catégories : 1G/1D (zone 0/20) → 2G/2D (zone 1/21) → 3G/3D (zone 2/22).",
        "Groupes de gaz : IIA (moins dangereux) → IIB → IIC (hydrogène, le plus dangereux).",
      ],
      legalRefs: [
        "Directive 99/92/CE (ATEX 137) transposée par décret 2002-1553 : obligations de l'employeur.",
        "Directive 2014/34/UE (ATEX 95, refonte 94/9/CE) : équipements utilisés en atmosphère explosive.",
        "Code du travail - Art. R4227-42 à R4227-54 : dispositions spécifiques aux atmosphères explosives.",
        "EN 60079-0 : exigences générales - équipements pour atmosphères explosives.",
        "EN 60079-10-1 (gaz) et EN 60079-10-2 (poussières) : classification des zones.",
        "Code du travail - Art. L4131-1 : droit d'alerte et de retrait du salarié.",
      ],
    },
    {
      id: "processus-accident",
      title: "3. Le processus menant à l'accident et la prévention",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-processus-accident.svg",
      chapterImageAlt: "Processus menant à l'accident ATEX — chaîne causale et 9 principes de prévention",
      intro:
        "Un accident ne survient jamais par hasard. Il résulte d'une combinaison de facteurs qui peuvent être identifiés et maîtrisés. Comprendre ce processus est la première étape pour agir efficacement.",
      content: [
        "Le processus menant à l'Accident du Travail (AT) implique la présence simultanée d'un phénomène dangereux, d'une exposition et d'un dommage. Chaque étape de ce processus peut être interrompue par des mesures de prévention adaptées.",
        "Un phénomène dangereux est la source potentielle du dommage (présence d'un gaz inflammable, d'une source d'inflammation, d'une poussière combustible). Une situation dangereuse est la situation dans laquelle une personne se trouve exposée à ce phénomène. L'événement dangereux est l'élément déclencheur (fuite, étincelle, choc mécanique).",
        "La démarche globale de prévention repose sur 9 principes généraux définis par le Code du travail : éviter les risques, évaluer ceux qui ne peuvent être évités, combattre les risques à la source, adapter le travail à l'homme, tenir compte de l'évolution de la technique, remplacer ce qui est dangereux, planifier la prévention, donner la priorité aux mesures de protection collective, et former et informer les travailleurs.",
        "La hiérarchie des mesures de prévention distingue trois niveaux : le risque important (à traiter en priorité), le risque limité (à réduire), et le risque évité (situation maîtrisée). L'objectif est toujours de descendre vers l'élimination du risque.",
        "Les principaux partenaires de la prévention sont : l'employeur (obligé de prendre les mesures), le service de prévention et de santé au travail (SPST), le Comité Social et Économique (CSE), l'Inspection du travail (IT), la CARSAT et l'organisme de prévention de la branche.",
      ],
      keyPoints: [
        "L'accident = phénomène dangereux + exposition + événement déclencheur.",
        "9 principes généraux de prévention définis par le Code du travail.",
        "Priorité aux mesures collectives sur les mesures individuelles.",
        "Les partenaires de la prévention (SPST, CSE, IT, CARSAT) ont un rôle d'appui.",
      ],
    },
    {
      id: "mecanisme-explosion",
      title: "4. Le mécanisme d'une explosion",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-explosion-dynamic.svg",
      chapterImageAlt: "Les 6 conditions simultanées de l'explosion — animation pulsante",
      visual: {
        title: "Domaine d'explosivité",
        subtitle: "Entre LIE et LSE : explosion possible. Seuil alarme explosimètre = 20 % LIE.",
        tone: "red" as const,
        animationKey: "atex-domaine-explosivite" as const,
      },
      intro:
        "Une explosion n'est pas un phénomène aléatoire. Elle nécessite 6 conditions simultanées. Supprimer l'une d'elles suffit à empêcher l'explosion.",
      content: [
        "Pour qu'une explosion se produise, 6 conditions doivent être réunies simultanément : un produit combustible (gaz, vapeur, poussière), un comburant (oxygène de l'air), une source d'inflammation, une concentration du combustible dans la plage explosive, un volume suffisant, et un confinement (partiel ou total).",
        "Le domaine d'explosivité est la plage de concentration du combustible dans l'air entre laquelle les explosions sont possibles. En dessous de la Limite Inférieure d'Explosivité (LIE), le mélange est trop pauvre. Au-dessus de la Limite Supérieure d'Explosivité (LSE), il est trop riche. L'explosion ne peut se produire qu'entre ces deux limites.",
        "Le point éclair est la température à partir de laquelle un combustible émet des vapeurs en quantité suffisante pour former un mélange inflammable avec l'air. La température d'auto-inflammation est la température à partir de laquelle les vapeurs émises s'enflamment spontanément sans source d'inflammation externe.",
        "Exemples de domaines d'explosivité : méthanol (LIE 5,5% - LSE 44%), essence (LIE 1,1% - LSE 7,5%), hydrogène (LIE 4% - LSE 75%). Le propane a une LIE de 1,7% et une LSE de 10,9%.",
        "Les effets d'une explosion incluent : onde de pression (souffle), projection de fragments, effets thermiques (boule de feu, flash), onde de détonation dans les cas les plus graves. Les conséquences peuvent être irréversibles pour les personnes et les structures.",
      ],
      deepDive: [
        "Dans la pratique, les poussières combustibles présentent un risque souvent sous-estimé. Les silos, broyeurs, convoyeurs et installations de séchage dans l'agroalimentaire, la menuiserie ou la métallurgie peuvent générer des nuages de poussières à concentration explosive.",
        "La teneur en oxygène joue un rôle clé : en dessous d'une Concentration Limite en Oxygène (CLO), l'explosion ne peut pas se produire. Certains procédés utilisent l'inertage (azote, CO2) pour maintenir l'atmosphère sous la CLO.",
        "L'indice Kst (pour les poussières) caractérise la vitesse d'augmentation de pression lors d'une explosion. Plus il est élevé, plus l'explosion est violente et rapide.",
      ],
      keyPoints: [
        "6 conditions simultanées requises pour une explosion : combustible, comburant, source d'inflammation, concentration entre LIE et LSE, volume, confinement.",
        "LIE = concentration minimale / LSE = concentration maximale pour une explosion.",
        "Le point éclair et la température d'auto-inflammation sont des indicateurs de danger.",
        "Les poussières combustibles sont un risque ATEX fréquemment sous-estimé.",
        "Supprimer une seule des 6 conditions empêche l'explosion.",
      ],
      legalRefs: [
        "Norme EN 1127-1 : atmosphères explosives — prévention de l'explosion et protection contre l'explosion.",
        "INERIS — Guides techniques sur les paramètres d'explosivité des gaz et poussières.",
      ],
    },
    {
      id: "zones-atex",
      title: "5. Zonage ATEX — classification et délimitation",
      estimatedMinutes: 30,
      chapterImagePath: "/elearning/atex/atex-classification-zones-semicercle.png",
      chapterImageAlt: "Classification des zones ATEX gaz (0/1/2) et poussières (20/21/22) — demi-cercle INERIS",
      intro:
        "L'une des étapes primordiales de la démarche d'évaluation du risque d'explosion est la délimitation des zones à risques (zonage ATEX). Ce zonage caractérise la possibilité de formation d'une atmosphère explosive, son volume et sa fréquence d'apparition.",
      content: [
        "La réglementation distingue deux grandes familles de zones ATEX : les zones gaz/vapeurs/brouillards (numérotées 0, 1, 2) et les zones poussières (numérotées 20, 21, 22). La classification repose sur la fréquence et la durée de présence d'une atmosphère explosive en fonctionnement normal.",
        "Zone 0 / Zone 20 (risque permanent) : atmosphère explosive présente en permanence ou pendant de longues périodes. Pour les gaz : intérieur des réservoirs, canalisations, récipients. Pour les poussières : intérieur des silos, broyeurs, systèmes de convoyage fermés. Catégorie d'appareil requise : 1G ou 1D.",
        "Zone 1 / Zone 21 (risque occasionnel) : atmosphère explosive susceptible de se présenter occasionnellement en fonctionnement normal. Pour les gaz : proximité immédiate de la zone 0, abords des ouvertures d'alimentation, évents, vannes de purge, points bas (fosses, caniveaux). Pour les poussières : emplacements à proximité des points de remplissage ou de vidange de poudre. Catégorie d'appareil requise : 2G ou 2D (ou 1G/1D).",
        "Zone 2 / Zone 22 (risque accidentel) : atmosphère explosive apparaissant accidentellement, en cas de dysfonctionnement ou pour de courtes durées seulement. Pour les gaz : emplacements entourant les zones 0 et 1, zones à proximité des brides, raccords de tuyauterie, appareils en matériaux fragiles ou équipements susceptibles de fuir. Pour les poussières : zones au voisinage d'appareils à partir desquels de la poussière peut s'échapper en cas de fuite (exemple : ateliers de broyage avec dépôts sur les éléments de charpente). Catégorie d'appareil requise : 3G ou 3D (ou 2G/1G, 2D/1D).",
        "Attention : les couches, dépôts et tas de poussières combustibles doivent également être traités comme sources susceptibles de former une atmosphère explosive — même sans nuage visible, un dépôt de poussière remis en suspension peut créer une atmosphère explosive en quelques secondes.",
        "Les locaux ou emplacements susceptibles de présenter une ou plusieurs zones ATEX doivent être signalés à l'aide du pictogramme réglementaire (triangle jaune avec flamme) à l'entrée de chaque zone. En fonction des mesures techniques et organisationnelles mises en place, le zonage final pourra éventuellement être moins contraignant en occurrence et/ou en volume.",
      ],
      deepDive: [
        "Cas particulier de la maintenance : les opérations d'entretien, de maintenance et les travaux par points chauds doivent faire l'objet d'une analyse des risques spécifique et de documents particuliers (bon d'intervention, permis de feu, plan de prévention pour les entreprises extérieures). Lors de ces opérations, les conditions ne sont pas celles du fonctionnement normal — elles peuvent être dégradées. Il est primordial d'identifier les risques, de supprimer les zones ATEX présentes (par exemple par la consignation de l'installation) et d'identifier les zones restantes ou créées par un zonage spécifique.",
        "Pour des opérations récurrentes d'entretien ou de maintenance, les ATEX temporaires créées doivent figurer dans le zonage de fonctionnement normal de l'installation.",
        "Exemple INERIS de zonage gaz : une ATEX zone 2 se forme à proximité d'une flaque d'un liquide à point d'éclair inférieur à l'ambiante répandu accidentellement, ou à proximité d'une canalisation sous pression présentant une fuite (dysfonctionnement). Ces cas illustrent la distinction entre zone 1 (fuite probable en fonctionnement normal) et zone 2 (fuite seulement en cas d'anomalie).",
      ],
      keyPoints: [
        "Zones gaz : 0 (permanent) → catégorie 1G | 1 (occasionnel) → 2G | 2 (accidentel) → 3G.",
        "Zones poussières : 20 → 1D | 21 → 2D | 22 → 3D.",
        "Dépôts et couches de poussières = source ATEX même sans nuage visible.",
        "Zonage spécifique obligatoire pour les opérations de maintenance.",
        "Tout intervenant doit connaître la classification exacte de la zone avant d'entrer.",
        "Le zonage doit figurer dans le DRPCE et être accessible à tous les intervenants.",
      ],
      legalRefs: [
        "Directive 99/92/CE (ATEX 137) — Annexe I : classification des emplacements dangereux.",
        "NF EN 60079-10-1 : classement des emplacements — atmosphères explosives gazeuses.",
        "NF EN 60079-10-2 : classement des emplacements — atmosphères explosives poussiéreuses.",
        "Guide INRS ED 945 — Mise en oeuvre de la réglementation relative aux atmosphères explosives.",
        "Guide INERIS DRA-07-83204-06985 — Méthodologie de classification des zones ATEX.",
      ],
      resourceVideos: [
        {
          title: "INRS — Prévention du risque ATEX",
          description:
            "Vidéo officielle de l'INRS sur la prévention des risques liés aux atmosphères explosives : formation des ATEX, zonage, mesures de prévention et obligations réglementaires.",
          url: "https://youtu.be/MaieQIweE0A",
          provider: "INRS",
          ctaLabel: "Voir la vidéo INRS",
        },
      ],
    },
    {
      id: "sources-inflammation",
      title: "6. Les sources d'inflammation en zone ATEX",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-sources-inflammation.svg",
      chapterImageAlt: "Les 6 familles de sources d'inflammation et les interdictions absolues en zone ATEX",
      intro:
        "Une source d'inflammation suffit à déclencher une explosion si une atmosphère explosive est présente. Il en existe de nombreux types, souvent insoupçonnés.",
      content: [
        "Les sources d'inflammation peuvent être de nature électrique : courants électriques vagabonds, échauffements, étincelles entre parties métalliques. Elles peuvent être mécaniques : frictions, chocs, échauffements résultant de défauts de lubrification. Elles peuvent être thermiques : surfaces chaudes (brûleurs, lampes, tuyauteries), travaux par points chauds (soudure, découpe, meulage).",
        "Sources chimiques (réactions) : la fermentation bactérienne peut échauffer le milieu et créer les conditions d'un auto-échauffement en présence d'oxygène.",
        "Sources électrostatiques : l'accumulation de charges par frottement (écoulement de liquides, transport de poussières) peut générer une étincelle suffisante pour enflammer une atmosphère explosive. Les risques sont particulièrement élevés lors du remplissage de cuves ou de la manipulation de poudres.",
        "Sources climatiques : l'impact de la foudre peut directement, ou par courant induit, créer une source d'inflammation dans une atmosphère explosive.",
        "Dans l'industrie, les produits inflammables sont souvent stockés dans des cuves à l'azote pour éviter tout contact avec l'air. Attention aux travaux par points chauds : une flamme nue ou une étincelle ne doit jamais être générée à proximité d'une atmosphère explosive sans permis de feu et autorisation spécifique.",
        "Les sources d'inflammation à contrôler en zone ATEX : détecteurs (pression, température, CO), thermographes, systèmes de contrôle du réseau de transport thermique ou hybride, systèmes de dépôt de billes poussiéreuses transbordées.",
      ],
      deepDive: [
        "Les travaux par points chauds (soudage, découpage, meulage, perçage) constituent la première cause d'accidents ATEX sur les sites industriels. Le permis de feu est obligatoire et doit inclure une vérification de l'atmosphère avant et pendant les travaux.",
        "Les vêtements synthétiques peuvent accumuler des charges électrostatiques et constituer une source d'inflammation. En zone ATEX, le port de vêtements antistatiques certifiés est obligatoire.",
        "Attention aux téléphones portables et appareils électroniques grand public : ils ne sont pas certifiés ATEX et constituent une source d'inflammation potentielle. Leur utilisation en zone ATEX est interdite sauf dérogation spécifique.",
      ],
      keyPoints: [
        "Sources d'inflammation : électriques, mécaniques, thermiques, chimiques, électrostatiques, climatiques.",
        "Travaux par points chauds = source principale d'accidents ATEX → permis de feu obligatoire.",
        "Appareils électroniques non certifiés ATEX interdits en zone.",
        "Vêtements antistatiques obligatoires en zone ATEX.",
        "Toute anomalie pouvant constituer une source d'inflammation doit être signalée immédiatement.",
      ],
      resourceVideos: [
        {
          title: "INRS — Permis de feu et travaux par points chauds en zone ATEX",
          description: "Les travaux par points chauds sont la première cause d'accidents ATEX. Cette vidéo INRS détaille les procédures : permis de feu, vérification atmosphère, conduite à tenir.",
          url: "https://youtu.be/1A6lYzE29Qo",
          provider: "INRS",
          ctaLabel: "Voir la vidéo INRS",
        },
      ],
    },
    {
      id: "risques-mesures-prevention",
      title: "7. Actions de prévention et mesures de protection",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-prevention-3axes.svg",
      chapterImageAlt: "Prévention ATEX — 3 axes d'action : combustible, sources d'inflammation, organisation",
      intro:
        "La prévention des risques ATEX repose sur une démarche structurée : agir sur le combustible, sur la source d'inflammation et sur les procédures. Aucune mesure seule ne suffit.",
      content: [
        "Pour éviter le risque lié aux combustibles : remplacer le produit combustible par un autre moins dangereux ou ininflammable, maintenir la concentration du combustible hors de son domaine d'explosivité (dilution, ventilation, aspiration), contrôler les fuites et les dépôts de poussières.",
        "Mesures sur les sources d'inflammation : utiliser uniquement des équipements certifiés pour la zone ATEX concernée, interdire les travaux par points chauds sans permis de feu, éliminer l'électricité statique (liaisons équipotentielles, matériaux conducteurs, mise à la terre), contrôler les surfaces chaudes.",
        "Procédures et organisation : établir un mode opératoire d'intervention, rédiger un plan de prévention, valider le travail par une personne compétente désignée par l'employeur, utiliser des autorisations de travail appropriées, organiser le nettoyage des zones et locaux.",
        "Actions sur le matériel : adéquation du matériel à la zone, outillage adapté, mise à la terre, liaison équipotentielle des équipements et installations. Le marquage Ex sur les équipements atteste de leur certification pour une utilisation en zone ATEX.",
        "Mesures de protection structurelle lorsqu'il n'est pas possible d'empêcher la formation d'une atmosphère explosive : extincteurs dédiés, suppresseurs d'explosions, appareils résistants à la surpression, systèmes de découplage technique (écluse rotative, vanne rapide), configuration des locaux (compartimentage, résistance des matériaux), ventilation.",
      ],
      deepDive: [
        "Les emplacements où des Atmosphères Explosives peuvent se former sont normalement signalés au niveau de leurs accès respectifs. Le pictogramme d'avertissement ATEX (triangle noir sur fond jaune avec une flamme) doit être visible à l'entrée de chaque zone.",
        "Les contrôles atmosphériques avant intervention sont essentiels : un explosimètre portable permet de mesurer la concentration du mélange inflammable dans l'air et de vérifier qu'on se trouve hors du domaine d'explosivité avant de démarrer les travaux.",
        "La ventilation est une mesure de prévention fondamentale : elle dilue l'atmosphère explosive et maintient la concentration sous la LIE. Elle doit être vérifiée et maintenue opérationnelle avant tout travail en zone.",
      ],
      keyPoints: [
        "Agir sur le combustible : dilution, ventilation, aspiration, substitution.",
        "Agir sur les sources d'inflammation : équipements certifiés Ex, permis de feu, liaisons équipotentielles.",
        "Agir sur l'organisation : mode opératoire, plan de prévention, autorisations de travail.",
        "Le marquage Ex = certification de l'équipement pour utilisation en zone ATEX.",
        "Contrôle atmosphérique obligatoire avant toute intervention en zone ATEX.",
      ],
      legalRefs: [
        "Directive 2014/34/UE (refonte 94/9/CE — ATEX équipements) — marquage CE + marquage Ex des équipements.",
        "Norme EN 13463-1 : appareils non électriques destinés à être utilisés en atmosphères explosibles.",
        "Guide INRS ED 6028 — Atmosphères explosives au travail.",
      ],
    },
    {
      id: "choix-materiaux-equipements",
      title: "8. Marquage et adéquation des équipements en zone ATEX",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-exemple-marquage-label.png",
      chapterImageAlt: "Exemple réel de marquage ATEX : II 2G Ex ib IIC T4 Gb / II 2D Ex ib IIIC T135°C Db IP64",
      visual: {
        imagePath: "/elearning/atex/atex-classes-temperature.svg",
        imageAlt: "Classes de température T1 à T6 — valeurs maximales de surface",
      },
      intro:
        "Tous les appareils présents en zone ATEX — électriques ET non électriques (pneumatique, hydraulique, mécanique) — doivent être conformes aux prescriptions techniques liées au type de zone. Un marquage spécifique permet de vérifier cette adéquation.",
      content: [
        "Marquage réglementaire (directive 2014/34/UE) : chaque équipement utilisé en zone ATEX doit porter le marquage CE suivi de la catégorie adaptée à la zone. Pour les industries de surface (groupe II) : catégorie 1G ou 1D pour les zones 0/20 (risque permanent), catégorie 2G ou 2D pour les zones 1/21 (risque occasionnel), catégorie 3G ou 3D pour les zones 2/22 (risque accidentel). Une catégorie supérieure peut toujours être utilisée dans une zone de niveau inférieur.",
        "Marquage normatif complémentaire : au-delà du marquage réglementaire, le marquage normatif permet de vérifier la compatibilité de l'équipement avec les caractéristiques physicochimiques du produit présent. Il indique : le mode de protection Ex (d, e, ia, ib, p, n, t...), le groupe de gaz (IIA, IIB, IIC pour les gaz/vapeurs — IIC étant le plus dangereux — ou IIIA, IIIB, IIIC pour les poussières), et la classe de température (T1 à T6).",
        "Modes de protection Ex : Ex d = enveloppe antidéflagrante (contient l'explosion interne), Ex e = sécurité augmentée (empêche les étincelles en fonctionnement normal), Ex ia/ib = sécurité intrinsèque (limite l'énergie), Ex p = surpression interne (gaz inerte empêche l'entrée de l'atmosphère explosive), Ex n = non-allumage en fonctionnement normal, Ex t = protection par enveloppe pour poussières.",
        "Classes de température : la température de surface de l'appareil est limitée par la classe T (T1 = 450°C, T2 = 300°C, T3 = 200°C, T4 = 135°C, T5 = 100°C, T6 = 85°C). Cette température doit toujours être inférieure à la température d'auto-inflammation du produit présent. Pour les poussières, la température maximale pouvant être atteinte est directement indiquée sur l'appareil.",
        "Indice de protection IP : pour les poussières, l'indice IP (étanchéité) est indiqué par les lettres IP suivies de deux chiffres — le premier pour l'étanchéité aux poussières (0 à 6), le second pour l'étanchéité aux liquides (0 à 8). Plus le chiffre est élevé, plus l'étanchéité est grande. En zone ATEX poussières, un IP élevé est généralement requis pour empêcher toute pénétration.",
        "L'outillage à main doit également être adapté : outils en alliage de cuivre ou de béryllium (non producteurs d'étincelles), outils certifiés ATEX. L'utilisation d'outillage ordinaire, d'un téléphone portable non certifié ou de tout appareil électronique grand public est strictement interdite. La détection d'une infraction doit conduire à l'arrêt immédiat du travail.",
      ],
      deepDive: [
        "Exemple de lecture d'un marquage ATEX complet : 'CE II 2G Ex e IIB T3 Gb' se lit : CE (conforme aux directives), II (industrie de surface), 2G (catégorie 2, pour zone 1, atmosphère gazeuse), Ex e (mode sécurité augmentée), IIB (groupe de gaz IIB — compatible avec IIA et IIB, pas IIC), T3 (température de surface max 200°C), Gb (EPL b = niveau de protection élevé pour gaz).",
        "Pour les poussières, un marquage typique serait : 'CE II 2D Ex tb IIIB T135°C Db IP65' — catégorie 2D pour zone 21, mode protection par enveloppe (tb), groupe poussières IIIB (conducteur), température maximale 135°C, indice de protection IP65.",
        "Attention à la norme IECEx (Commission Electrotechnique Internationale) : largement utilisée hors Europe et Amérique du Nord, elle est souvent mentionnée sur les fiches techniques des appareils importés. Les classifications de zones et les catégories sont équivalentes mais la notation peut différer légèrement.",
      ],
      keyPoints: [
        "Catégorie 1G/1D → zones 0/20 | 2G/2D → zones 1/21 | 3G/3D → zones 2/22.",
        "Marquage normatif : mode Ex + groupe gaz (IIA/IIB/IIC) + classe température (T1→T6).",
        "T6 = 85°C max : pour les produits à basse température d'auto-inflammation.",
        "IIC = groupe le plus dangereux (hydrogène, acétylène) — exige des appareils spécifiques.",
        "IP élevé obligatoire en zone poussières pour éviter toute pénétration.",
        "Une catégorie supérieure peut toujours être utilisée dans une zone de niveau inférieur.",
      ],
      legalRefs: [
        "Directive 2014/34/UE (ATEX 95) — catégories d'appareils et marquage réglementaire.",
        "NF EN 60079-0 : exigences générales — équipements pour atmosphères explosives.",
        "Guide INRS ED 945 — Mise en oeuvre de la réglementation relative aux atmosphères explosives.",
        "INRS ED 6028 — Atmosphères explosives au travail : tableau récapitulatif des équipements par zone.",
        "Norme IECEx — équivalences internationales hors Europe.",
      ],
      resourceVideos: [
        {
          title: "INRS — Marquage et sélection des équipements ATEX",
          description: "Comment lire un marquage Ex et choisir le bon équipement selon la zone ATEX. Groupes de gaz, catégories, modes de protection et classes de température.",
          url: "https://youtu.be/vhswVTHEbRQ",
          provider: "INRS",
          ctaLabel: "Voir la vidéo INRS",
        },
      ],
    },
    {
      id: "epi-atex",
      title: "9. Équipements de Protection Individuelle (EPI) en zone ATEX",
      estimatedMinutes: 15,
      chapterImagePath: "/elearning/atex/atex-fiche-epi-mabeo.png",
      chapterImageAlt: "Fiche EPI ATEX Mabéo : casque EN 397/A1, vêtements antistatiques EN ISO 14116 + EN ISO 11612, gants isolants EN 60903, chaussures EN ISO 20345, tenue EN 1149",
      intro:
        "Les EPI en zone ATEX ont des exigences spécifiques et normées. Chaque article doit être antistatique, certifié et adapté aux risques chimiques et thermiques de la zone. Les normes sont vérifiables sur chaque équipement.",
      content: [
        "Casque de protection : norme EN 397/A1 avec mention ESD (antistatique). Le casque doit dissiper les charges électrostatiques accumulées pour ne pas constituer une source d'inflammation. Les casques en plastique non conducteur sont interdits en zone ATEX.",
        "Vêtements de travail antistatiques : deux normes complémentaires s'appliquent. EN ISO 14116 (protection contre la chaleur et les flammes — comportement des matériaux à flamme limitée) et EN ISO 11612 (vêtements de protection contre la chaleur et les flammes pour les travaux dans l'industrie). La norme EN 1149-5 régit la résistance antistatique des vêtements : la résistance superficielle doit être inférieure à 2,5 × 10^9 Ω. Les vêtements synthétiques non conformes sont strictement interdits.",
        "Gants isolants : norme EN 60903 (gants en matériaux isolants pour les travaux sous tension). En zone ATEX avec risques électriques, les gants doivent être testés à la tension appropriée et vérifiés avant chaque utilisation. Les gants en latex naturel ne sont pas adaptés aux produits chimiques des zones ATEX pétrolières.",
        "Chaussures de sécurité antistatiques : norme EN ISO 20345 avec propriété ESD (Electrostatic Dissipative). La résistance électrique doit être comprise entre 100 kΩ et 1000 MΩ pour dissiper les charges sans constituer un risque de choc électrique. Selon les risques chimiques présents, une résistance aux hydrocarbures est également requise.",
        "Détecteur de gaz portable (explosimètre) : indispensable pour tout intervenant en zone ATEX. L'appareil doit être certifié Ex (marquage ATEX), adapté aux gaz ou poussières présents, et étalonné régulièrement selon les préconisations du fabricant. L'alarme basse doit être réglée à 20 % de la LIE pour permettre l'évacuation en toute sécurité avant l'atteinte du domaine explosif.",
        "Protection respiratoire : selon la nature et la concentration des produits présents, un appareil de protection respiratoire (demi-masque avec filtre adapté, masque complet, ARI) peut être nécessaire. En atmosphère IDLH (Immediately Dangerous to Life or Health), l'ARI autonome à air comprimé est obligatoire. Le filtre doit correspondre aux produits en présence (A pour solvants organiques, B pour gaz acides, P pour particules).",
        "Tous les EPI doivent être vérifiés avant chaque utilisation, entretenus conformément aux notices fabricants, stockés dans des conditions adaptées et remplacés dès qu'ils présentent une anomalie, une dégradation ou qu'ils ont dépassé leur date de péremption.",
      ],
      keyPoints: [
        "Casque ESD : EN 397/A1 — dissipation des charges électrostatiques.",
        "Vêtements antistatiques : EN 1149-5 + EN ISO 14116 + EN ISO 11612 (protection thermique et flammes).",
        "Gants isolants : EN 60903 — vérification avant chaque utilisation.",
        "Chaussures ESD : EN ISO 20345 — résistance 100 kΩ à 1000 MΩ.",
        "Explosimètre certifié Ex : alarme basse à 20 % de la LIE — étalonnage régulier.",
        "Filtres respiratoires adaptés aux produits présents — ARI obligatoire en IDLH.",
      ],
    },
    {
      id: "signalisation-atex",
      title: "10. Signalisation et comportements en zone ATEX",
      estimatedMinutes: 15,
      chapterImagePath: "/elearning/atex/atex-panneau-zone-interdictions.png",
      chapterImageAlt: "Panneau Zone ATEX avec 3 interdictions réglementaires : no fumer, pas de flamme nue, pas de téléphone non certifié",
      intro:
        "La signalisation ATEX est réglementaire et identique sur tous les sites. La connaître, la respecter et adopter les bons comportements peut éviter une catastrophe.",
      content: [
        "Le pictogramme ATEX réglementaire est un triangle d'avertissement noir sur fond jaune avec une flamme noire à l'intérieur. Ce signe doit être apposé à l'entrée de chaque zone ATEX, sur les équipements certifiés Ex et sur les emballages de produits inflammables.",
        "Les zones ATEX doivent être délimitées physiquement (balisage, signalétique) et leur accès contrôlé. Tout personnel non formé et non habilité doit en être exclu.",
        "Les bonnes pratiques en zone ATEX : respecter les prescriptions de sécurité définies dans l'autorisation de travail, signaler toute détérioration ou anomalie de matériel, ne pas utiliser un téléphone portable standard, ne pas fumer, ne pas utiliser un outillage non adapté, ne pas régler un matériel si on n'en a pas reçu une formation spécifique.",
        "Les comportements NON acceptables : fumer en zone ATEX, utiliser un outil produisant des étincelles, utiliser un équipement non certifié, ignorer une alerte de l'explosimètre, forcer l'accès à une zone condamnée, réaliser des travaux par points chauds sans permis de feu.",
        "En cas d'alarme ou de détection d'une atmosphère explosive : arrêter immédiatement le travail, évacuer la zone sans courir (éviter les étincelles mécaniques), alerter le responsable et les secours, ne pas allumer ni éteindre des sources électriques en quittant la zone.",
      ],
      practicalCase:
        "Un technicien de maintenance doit intervenir sur une pompe en zone 1 (gaz). Il constate que la zone est balisée ATEX. Il doit : vérifier qu'il possède une autorisation de travail pour cette zone, s'équiper de son EPI complet (vêtements antistatiques, chaussures ESD, gants adaptés, détecteur de gaz), vérifier la concentration atmosphérique avec son explosimètre avant d'entrer, utiliser uniquement des outils certifiés Ex, ne pas utiliser son téléphone portable, et alerter immédiatement si son détecteur sonne l'alarme.",
      keyPoints: [
        "Pictogramme ATEX = triangle jaune avec flamme noire → zone à risque d'explosion.",
        "Accès contrôlé : seules les personnes formées et habilitées peuvent entrer en zone ATEX.",
        "En cas d'alarme : arrêt travail + évacuation calme + alerte responsable.",
        "Zéro tolérance pour : cigarette, outil non certifié, équipement non Ex, travaux sans permis.",
        "La signalisation ATEX a force de réglementation : l'ignorer expose à des sanctions.",
      ],
      legalRefs: [
        "Directive 92/58/CEE transposée par le décret 2003-296 : prescriptions minimales de signalisation de sécurité.",
        "Directive 99/92/CE — Annexe III : signalisation des emplacements où des atmosphères explosives peuvent se former.",
      ],
    },
    {
      id: "conduite-accident",
      title: "11. Conduite à tenir en cas d'accident ou d'alerte ATEX",
      estimatedMinutes: 15,
      chapterImagePath: "/elearning/atex/atex-peas-urgence.svg",
      chapterImageAlt: "Conduite à tenir en urgence ATEX : 4 étapes PEAS — Protéger, Examiner, Alerter, Secourir",
      visual: {
        title: "Réflexes PEAS en urgence",
        subtitle: "4 étapes dans l'ordre : Protéger → Examiner → Alerter → Secourir",
        tone: "red" as const,
        animationKey: "peas-sst" as const,
      },
      intro:
        "Face à une situation d'urgence ATEX, les réflexes doivent être automatiques. Chaque seconde compte et une mauvaise réaction peut aggraver la situation.",
      content: [
        "En cas d'alarme ou de signal d'alerte (détecteur de gaz, odeur anormale, fuite visible) : PROTÉGER — identifier les risques persistants, éloigner les personnes de la zone dangereuse, baliser ou condamner l'accès, éliminer si possible les sources d'inflammation (sans créer de nouvelles étincelles).",
        "EXAMINER : la victime est-elle consciente ? Répond-elle ? Respire-t-elle ? Cette évaluation rapide guide l'alerte et les premiers secours.",
        "ALERTER : contacter les secours (15, 18, 112 ou SAMU), donner le maximum d'informations : lieu précis, nature des produits impliqués, nombre de victimes, état des victimes, nature de l'accident (explosion, intoxication, brûlure). Rester en ligne avec les secours.",
        "SECOURIR : en attendant les secours, adopter les gestes de premiers secours adaptés à la situation (mise en position de sécurité, PLS, massage cardiaque si nécessaire et si formé). Ne jamais entrer dans une zone d'atmosphère explosive sans équipement adapté pour porter secours.",
        "Les conséquences des AT et MP peuvent être physiques (douleurs, blessures, brûlures, intoxication, handicap), administratives (enquête AT, sanctions), financières (indemnités, frais médicaux, perte de salaire) et morales (impact sur la qualité de vie, image de l'entreprise).",
      ],
      keyPoints: [
        "Réflexe : PROTÉGER → EXAMINER → ALERTER → SECOURIR (PEAS).",
        "Ne jamais entrer dans une atmosphère explosive sans EPI adaptés pour porter secours.",
        "Donner un maximum d'informations aux secours : produits, victimes, localisation.",
        "Tout accident ATEX doit faire l'objet d'une déclaration et d'une analyse.",
        "Le numéro national de toxicologie (centres antipoison) : 09 74 75 67 50.",
      ],
    },
    {
      id: "recapitulatif",
      title: "12. Synthèse — Les 13 réflexes en zone ATEX",
      estimatedMinutes: 10,
      chapterImagePath: "/elearning/atex/atex-bonnes-pratiques-inrs.png",
      chapterImageAlt: "INRS — Atmosphères explosives : les bonnes pratiques ATEX (affiche officielle)",
      intro:
        "Mémo des comportements essentiels à retenir et à appliquer systématiquement lors de toute intervention en zone ATEX.",
      content: [
        "1. Connaître la classification ATEX de la zone avant d'entrer (zone 0/1/2 gaz ou 20/21/22 poussières).",
        "2. Posséder une autorisation de travail valide avant toute intervention.",
        "3. Porter tous les EPI prescrits : vêtements antistatiques, chaussures ESD, gants adaptés.",
        "4. Utiliser uniquement des équipements certifiés Ex adaptés à la zone concernée.",
        "5. Contrôler l'atmosphère avec un explosimètre certifié Ex avant d'entrer et pendant l'intervention.",
        "6. Ne jamais utiliser un téléphone portable standard ou un équipement électronique non certifié.",
        "7. Interdire absolument de fumer ou d'utiliser une flamme nue en zone ATEX.",
        "8. Obtenir un permis de feu avant tout travail par points chauds (soudure, meulage, découpe).",
        "9. Assurer la liaison équipotentielle et la mise à la terre des équipements.",
        "10. Signaler immédiatement toute fuite, toute anomalie d'équipement ou toute dégradation de signalisation.",
        "11. En cas d'alarme du détecteur de gaz : arrêt immédiat + évacuation calme + alerte responsable.",
        "12. Ne jamais sous-estimer le risque poussières : maintenir les locaux propres, éviter les dépôts.",
        "13. Participer aux formations et exercices ATEX organisés par l'employeur.",
      ],
      keyPoints: [
        "Autorisation de travail + EPI + explosimètre = trio indispensable avant toute intervention.",
        "Zéro improvisation en zone ATEX.",
        "Signalement systématique de toute anomalie, même mineure.",
        "La prévention ATEX est l'affaire de tous : employeur ET salarié.",
      ],
    },
  ],
  resourceFiles: [
    {
      title: "Livret Stagiaire ATEX Niveau 0",
      description:
        "Support de formation complet : 12 modules illustrés avec photos réelles (INERIS/INRS), tableaux de zonage, normes EPI, réflexes PEAS et QCM de 10 questions. À conserver comme référence après la formation.",
      url: "/downloads/atex/ATEX_N0_Livret_Stagiaire.pdf",
      fileType: "pdf",
      ctaLabel: "Télécharger le livret (PDF)",
    },
  ],
};
