import type { ModuleContent } from "./module-types";

export const atexNiveau1ModuleContent: ModuleContent = {
  title: "Formation et Sensibilisation ATEX NIV 1 Intervenant",
  shortTitle: "ATEX NIV 1",
  subtitle:
    "Parcours e-learning approfondi destiné au personnel intervenant directement sur des appareils ou installations situés en zone ATEX : techniciens de maintenance, électriciens, monteurs, instrumentistes, sous-traitants effectuant des travaux en zone classée.",
  duration: "5 h à 6 h",
  deliveryFormat: "E-learning autonome 5h-6h + classe virtuelle 4h avec formateur",
  level: "Intermédiaire",
  objective:
    "Maîtriser les règles d'intervention en zone ATEX : lire un marquage Ex complet, sélectionner l'équipement adapté à la zone, utiliser correctement l'explosimètre, appliquer les procédures d'autorisation de travail et permis de feu, utiliser les EPI antistatiques et réagir face à une anomalie ou un incident.",
  audience:
    "Personnel effectuant des travaux, de la maintenance ou des dépannages en zone ATEX : techniciens de maintenance industrielle, électriciens, instrumentistes, monteurs, chaudronniers, agents de nettoyage industriel, sous-traitants amenés à intervenir sur des équipements ou installations en zone classée.",
  certificationNote:
    "Ce parcours constitue la composante théorique d'une habilitation ATEX NIV 1 (Intervenant), conforme à la directive 99/92/CE, à l'arrêté du 8 juillet 2003 et aux articles R.4227-42 à R.4227-54 du Code du travail. Son contenu est élaboré en référence au Guide ISM-ATEX de l'INERIS, référentiel de bonnes pratiques reconnu pour la formation des intervenants en zone classée. À l'issue du e-learning, une classe virtuelle de 4 heures avec un formateur PREVENSIA (session Zoom) valide les acquis sur des cas pratiques et des mises en situation, et permet de délivrer l'avis d'habilitation ATEX NIV 1, valable 3 ans. La mise en situation pratique sur les installations du site et la prise en compte des spécificités terrain restent de la responsabilité de l'employeur.",
  heroBadge: "ATEX NIV 1",
  finalMessage:
    "En zone ATEX, intervenir sans les bons équipements, sans autorisation de travail ou sans vérification préalable de l'atmosphère expose l'intervenant et ses collègues à un risque mortel. Chaque étape — vérification de l'explosimètre, port des EPI antistatiques, respect du permis de feu — est un maillon de la chaîne de prévention. La classe virtuelle de 4 heures avec votre formateur PREVENSIA vous permettra de valider ces acquis appliqués à votre contexte réel, sur des cas pratiques issus de votre secteur d'activité.",
  quizCtaLabel: "Passer au quiz ATEX NIV 1",
  sections: [
    {
      id: "rappels-approfondissement",
      title: "1. Rappels et approfondissement — Le mécanisme de l'explosion",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-hexagone-lie-lse.png",
      chapterImageAlt: "Les 6 conditions simultanées d'une explosion ATEX et le domaine d'explosivité LIE/LSE — source INRS",
      visual: {
        title: "Domaine d'explosivité",
        subtitle: "Entre LIE et LSE : explosion possible. Seuil alarme = 20 % LIE.",
        tone: "red" as const,
        animationKey: "atex-domaine-explosivite" as const,
      },
      intro:
        "Avant d'intervenir en zone ATEX, il est indispensable de maîtriser parfaitement le mécanisme d'une explosion. Ce chapitre consolide les acquis du Niveau 0 et approfondit les paramètres physico-chimiques essentiels pour un intervenant.",
      content: [
        "Une explosion ATEX nécessite la réunion simultanée de 6 conditions : une substance combustible (gaz, vapeur, brouillard ou poussière), un comburant (l'oxygène de l'air), une concentration dans le domaine d'explosivité (entre LIE et LSE), un mélange homogène, un confinement ou un espace suffisant, et une source d'inflammation. Supprimer l'une de ces conditions suffit à éviter l'explosion.",
        "La Limite Inférieure d'Explosivité (LIE) et la Limite Supérieure d'Explosivité (LSE) définissent le domaine d'explosivité d'un gaz. Exemple : le méthane a une LIE de 5 % et une LSE de 15 % dans l'air. En dehors de ce domaine, pas d'explosion. Pour les interventions, le seuil d'alerte est fixé à 20 % de la LIE par les bonnes pratiques (circulaire du 9 mai 1985).",
        "Pour les poussières, la Concentration Minimale d'Explosion (CME) joue le rôle de LIE. Une couche de poussières de quelques millimètres d'épaisseur mise en suspension peut générer une ATEX. Les poussières de diamètre supérieur à 0,5 mm (500 µm) ne peuvent généralement pas former d'ATEX, mais ce critère est à vérifier selon la nature et le contexte.",
        "Le point d'éclair d'un liquide est la température minimale à laquelle il émet suffisamment de vapeurs pour former un mélange inflammable. Pour les calculs de sécurité, l'INERIS recommande de retrancher 15 °C au point d'éclair pour les produits complexes et mélanges, et 5 °C pour les produits purs bien documentés.",
        "La température d'auto-inflammation (TAI) est la température à laquelle un mélange s'enflamme spontanément sans source d'inflammation externe. Elle est critique pour le choix des équipements Ex (classes de température T1 à T6). Un équipement doit avoir une température maximale de surface inférieure à la TAI du mélange dans lequel il peut être utilisé.",
      ],
      deepDive: [
        "Groupes de gaz selon leur sensibilité à l'inflammation : IIA (propane, butane — les moins dangereux), IIB (éthylène, gaz de ville), IIC (hydrogène, acétylène — les plus dangereux, LIE très basse). Un équipement certifié IIC peut être utilisé pour les groupes IIA et IIB, mais pas l'inverse.",
        "Classes de température Ex : T1 (450 °C max) → T6 (85 °C max). Plus le numéro est élevé, plus la contrainte est sévère. Exemple : l'acétone a une TAI de 465 °C → équipement T1 suffisant. L'éther diéthylique a une TAI de 160 °C → équipement T4 ou mieux obligatoire.",
        "Pour les poussières, la norme EN 80079-20-2 donne les paramètres d'explosivité (CME, MIT — Minimum Ignition Temperature en couche et en nuage). La température maximale de surface de l'équipement doit être inférieure à MIT couche − 75 °C, ou à 2/3 × MIT nuage (la valeur la plus basse étant retenue).",
      ],
      keyPoints: [
        "6 conditions simultanées = explosion possible. Supprimer 1 = pas d'explosion.",
        "LIE / LSE : domaine d'explosivité. Seuil d'alarme explosimètre = 20 % de la LIE.",
        "CME pour poussières = équivalent de la LIE pour les gaz.",
        "Point d'éclair : température à partir de laquelle un liquide émet des vapeurs inflammables.",
        "Classe de température Ex : la température maxi de surface doit être < TAI du mélange.",
      ],
      legalRefs: [
        "Code du travail - Art. R.4227-42 : évaluation des risques d'explosion.",
        "Arrêté du 8 juillet 2003 : obligations de l'employeur en matière de protection contre les explosions.",
        "Norme EN 80079-20-1 : paramètres physico-chimiques des gaz et liquides inflammables.",
        "Norme EN 80079-20-2 : paramètres d'explosivité des poussières.",
      ],
      resourceVideos: [
        {
          title: "Explosion sur le lieu de travail — Zonage et marquage des appareils ATEX",
          description:
            "Vidéo INRS présentant les mécanismes d'explosion en milieu professionnel, le classement des zones ATEX et la lecture du marquage des matériels certifiés Ex.",
          url: "https://youtu.be/MaieQIweE0A?si=-oXQk8VzGFjGrUOA",
          provider: "INRS / YouTube",
          ctaLabel: "Voir la vidéo INRS",
        },
      ],
    },
    {
      id: "classification-zones-avancee",
      title: "2. Classification des zones ATEX — Critères et délimitation",
      estimatedMinutes: 30,
      chapterImagePath: "/elearning/atex/atex-classification-zones-cercle.png",
      chapterImageAlt: "Classification zones ATEX — cercles concentriques gaz/vapeurs/poussières zones 0-1-2 et 20-21-22",
      intro:
        "La classification des zones est la base du choix des équipements. Un intervenant doit savoir lire un plan de zonage, comprendre les critères qui définissent chaque zone et adapter son comportement en conséquence.",
      content: [
        "Les zones ATEX gaz/vapeurs : Zone 0 — atmosphère explosive présente en permanence ou pendant de longues périodes (intérieur d'un réservoir, d'une canalisation sous pression de gaz inflammable). Zone 1 — atmosphère explosive présente occasionnellement en fonctionnement normal (proximité d'un évent, d'une bride de tuyauterie). Zone 2 — atmosphère explosive présente rarement et pendant de courtes durées seulement, lors d'un dysfonctionnement ou incident (zone périphérique autour d'une zone 1).",
        "Les zones ATEX poussières : Zone 20 — nuage de poussières présent en permanence (intérieur d'un silo, d'un filtre à manches). Zone 21 — nuage de poussières présent occasionnellement (proximité d'un point de chargement/déchargement). Zone 22 — nuage de poussières présent rarement et brièvement (accumulation de dépôts pouvant être mis en suspension accidentellement).",
        "L'étendue de la zone dépend de la quantité de substance inflammable pouvant se libérer, de la densité du gaz par rapport à l'air (gaz plus léger = montée, gaz plus lourd = accumulation en point bas), des conditions de ventilation et de la température ambiante par rapport au point d'éclair.",
        "En phase de maintenance, des zones temporaires peuvent apparaître. L'INERIS distingue 3 situations : interventions de maintenance EN zone ATEX existante (analyser, consigner les fluides en priorité), interventions de maintenance GÉNÉRANT une zone ATEX (surveillance explosimètre continue), interventions SUR des sources d'inflammation (ouverture d'équipements électriques, travaux par points chauds).",
        "Le plan de zonage ATEX fait partie du DRPCE. Avant toute intervention, l'intervenant doit consulter ce document ou se renseigner auprès du responsable sécurité pour connaître la classification précise de la zone où il va travailler.",
      ],
      deepDive: [
        "Les zones ATEX doivent être signalées par le panneau triangulaire réglementaire (triangle noir sur fond jaune avec une flamme noire à l'intérieur et l'inscription 'ATEX'). Attention : ce pictogramme représente une flamme, pas un éclair — l'éclair est le symbole du risque électrique. À l'intérieur de la zone, seuls les équipements certifiés pour la catégorie correspondante sont autorisés.",
        "La maintenance peut modifier temporairement les zones : l'ouverture d'une vanne ou d'un équipement contenant un fluide inflammable crée une zone temporaire. Ces zones temporaires doivent être identifiées dans le plan de prévention ou le permis de travail.",
        "En présence de poussières : les couches de dépôts doivent être incluses dans le zonage. Une couche de 1 à 5 mm peut suffire à créer une zone 22 lors d'une mise en suspension (coup de pied, nettoyage à air comprimé). Le nettoyage des dépôts fait partie des mesures préventives obligatoires.",
      ],
      keyPoints: [
        "Zone 0/20 = présence permanente. Zone 1/21 = présence occasionnelle. Zone 2/22 = présence rare.",
        "La densité du gaz détermine son comportement : plus léger que l'air → monte, plus lourd → s'accumule en point bas.",
        "3 situations de maintenance selon l'INERIS : EN zone, GÉNÉRANT une zone, SUR des sources d'inflammation.",
        "En maintenance : consulter le DRPCE et identifier les zones temporaires avant intervention.",
        "Les couches de poussières doivent être nettoyées régulièrement — elles constituent une zone 22 latente.",
      ],
      legalRefs: [
        "Arrêté du 8 juillet 2003 - Art. 2 : définition et classification des emplacements dangereux.",
        "Code du travail - Art. R.4227-44 : signalisation des zones ATEX.",
        "Guide INERIS Omega 36 (octobre 2025) : méthodologie de classification et exemples.",
        "Normes EN 60079-10-1 (zones gaz) et EN 60079-10-2 (zones poussières).",
      ],
    },
    {
      id: "marquages-ex",
      title: "3. Lecture des marquages Ex — Décoder un équipement certifié",
      estimatedMinutes: 35,
      chapterImagePath: "/elearning/atex/atex-exemple-marquage-label.png",
      chapterImageAlt: "Exemple réel d'étiquette ATEX annotée : II 2G Ex ib IIC T4 Gb / II 2D Ex ib IIIC T135°C Db IP64 — décodage complet",
      intro:
        "Utiliser un équipement non adapté à la zone classée peut provoquer une explosion. Savoir lire un marquage Ex complet est une compétence fondamentale pour tout intervenant en zone ATEX.",
      content: [
        "Le marquage Ex complet se décompose en 5 éléments : (1) Le marquage CE (conformité réglementaire européenne). (2) Le symbole Ex (protection contre les explosions). (3) Le groupe d'appareils : II pour les surfaces, I pour les mines de grisou. (4) La catégorie : 1G/2G/3G (gas) ou 1D/2D/3D (dust — poussières). (5) Le mode de protection : Ex d (enveloppe antidéflagrante), Ex e (sécurité augmentée), Ex ia/ib (sécurité intrinsèque), Ex p (surpression interne), Ex n (non-incendiaire), Ex t (protection par enveloppe).",
        "Correspondance catégorie ↔ zone : Catégorie 1G → utilisable en zones 0, 1 et 2. Catégorie 2G → utilisable en zones 1 et 2 uniquement. Catégorie 3G → utilisable en zone 2 uniquement. Même logique pour les poussières : 1D → zones 20, 21, 22 / 2D → zones 21 et 22 / 3D → zone 22 uniquement. RÈGLE : la catégorie doit être au moins égale à la zone (1 = plus restrictif, 3 = moins restrictif).",
        "Le groupe de gaz indique la dangerosité : IIA (propane) → IIB (éthylène) → IIC (hydrogène, acétylène). Un équipement certifié IIC convient à tous les groupes. Un équipement IIA est INTERDIT en zone IIB ou IIC.",
        "La classe de température indique la température maximale de surface : T1 = 450 °C, T2 = 300 °C, T3 = 200 °C, T4 = 135 °C, T5 = 100 °C, T6 = 85 °C. Elle doit être inférieure à la température d'auto-inflammation du mélange présent dans la zone.",
        "Exemple de marquage complet : ⓔ Ex d IIB T4 Gb. Décodage : Ex = certifié ATEX, d = enveloppe antidéflagrante, IIB = groupe gaz éthylène, T4 = température max 135 °C, Gb = equipment protection level b (niveau de protection élevé). Ce matériel est utilisable en zone 1 ou 2 pour des atmosphères de gaz/vapeurs du groupe IIB.",
      ],
      deepDive: [
        "Depuis la directive 2014/34/UE (transposée en droit français aux articles R.557-1-1 et suivants du Code de l'environnement), les matériels ATEX doivent être livrés avec la déclaration UE de conformité et la notice d'instructions dans la langue du pays d'utilisation. L'absence de ces documents constitue une non-conformité contrôlable par l'inspection du travail ou la DREAL.",
        "La directive 2014/34/UE autorise les fabricants à réaliser une autocertification pour les matériels de catégorie 3 et les matériels non électriques de catégorie 2. Pour les matériels électriques de catégorie 1 et 2, l'intervention d'un organisme notifié est obligatoire. L'utilisateur doit toujours vérifier la présence du marquage CE + Ex.",
        "Cas des matériels anciens (avant 2003) : les équipements mis en service avant le 30 juin 2003 conformes à l'arrêté du 19 décembre 1988 peuvent rester en service si le DRPCE les a validés explicitement avant le 1er juillet 2006. Ces matériels portent des marquages différents (pas de marquage CE Ex) et doivent être identifiés dans le DRPCE.",
      ],
      keyPoints: [
        "Catégorie 1 = zone 0/20/1/21/2/22. Catégorie 2 = zone 1/21/2/22. Catégorie 3 = zone 2/22 uniquement.",
        "Groupe de gaz : IIA < IIB < IIC (du moins au plus dangereux). Un matériel IIC convient partout.",
        "Classe de température : T1 (plus permissif) → T6 (le plus restrictif). Temp. surface < TAI mélange.",
        "Tout équipement ATEX neuf = déclaration UE conformité + notice obligatoires.",
        "JAMAIS utiliser un équipement non marqué Ex ou de catégorie insuffisante dans une zone classée.",
      ],
      legalRefs: [
        "Directive 2014/34/UE : exigences pour les appareils ATEX destinés aux atmosphères explosibles.",
        "Code du travail - Art. R.4321-1 : responsabilité de l'employeur pour le choix des équipements.",
        "Code de l'environnement - Art. R.557-1-1 à R.557-5-5 : transposition de la directive 2014/34/UE.",
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 5 : sélection et installation des équipements.",
      ],
      resourceVideos: [
        {
          title: "Zonage et marquage des matériels ATEX — Lecture du marquage Ex complet",
          description:
            "Vidéo INRS expliquant comment déchiffrer le marquage Ex d'un équipement certifié ATEX : symbole Ex, groupe d'appareils, catégorie, mode de protection et classe de température.",
          url: "https://youtu.be/vhswVTHEbRQ?si=iyeYJYqstsuEzHfT",
          provider: "INRS / YouTube",
          ctaLabel: "Voir la vidéo — Marquage Ex",
        },
      ],
    },
    {
      id: "autorisation-travail-permis-feu",
      title: "4. DRPCE, autorisation de travail et permis de feu en zone ATEX",
      estimatedMinutes: 35,
      chapterImagePath: "/elearning/atex/atex-panneau-porte.png",
      chapterImageAlt: "Panneau ATEX sur une porte industrielle : ce local contient des zones ou des équipements avec risque d'explosion",
      intro:
        "L'autorisation de travail et le permis de feu sont des outils organisationnels essentiels pour maîtriser les risques lors d'interventions en zone ATEX. Leur non-respect est à l'origine de nombreux accidents graves.",
      content: [
        "L'autorisation de travail (AT) est un document écrit délivré par le responsable de l'installation avant toute intervention en zone classée. Elle précise : la nature et le lieu de l'intervention, les conditions de zone (présence ou non d'ATEX), les mesures de prévention à mettre en œuvre (ventilation, consignation, détection), les équipements et EPI à utiliser, et la durée de validité de l'autorisation.",
        "Le permis de feu est une autorisation de travail spécifique aux travaux générant des points chauds : soudage, découpe, meulage, tronçonnage, perçage, utilisation d'appareils de chauffage. Ces opérations génèrent des étincelles (~1 000 °C) et des surfaces chaudes susceptibles d'enflammer une grande majorité de produits.",
        "Zone de sécurité pour les travaux par points chauds : l'INERIS préconise une zone de sécurité de 10 mètres autour du point de travail. Cette zone doit être vérifiée au moyen d'un explosimètre AVANT le début des travaux et surveillée en continu PENDANT les travaux. Attention aux travaux en hauteur : les étincelles ou scories peuvent retomber loin de la zone d'intervention.",
        "Avant de commencer tout travail dans une zone ATEX : (1) Vérifier que l'autorisation de travail ou le permis de feu est signé et valide. (2) Mesurer l'atmosphère avec l'explosimètre (valeur < 20 % de la LIE). (3) Contrôler ses EPI antistatiques. (4) Identifier la sortie de secours la plus proche. (5) S'assurer de la disponibilité d'un moyen de communication avec le PC de sécurité.",
        "À la fin de l'intervention : restituer le permis de feu, consigner dans le registre, informer le responsable de la fin d'intervention et de l'état des lieux. Si une anomalie a été détectée pendant les travaux, elle doit être signalée immédiatement au responsable sécurité du site.",
      ],
      deepDive: [
        "En présence d'entreprises extérieures, l'article R.4515-8 du Code du travail impose un protocole de sécurité incluant les risques ATEX. L'entreprise d'accueil doit fournir aux prestataires les informations sur les zones classées et les procédures à respecter. Le plan de prévention doit intégrer les risques ATEX dès lors que des travaux sont réalisés en zone classée.",
        "L'expérience montre que les travaux par points chauds sont systématiquement sous-estimés comme source d'inflammation. Même si les travaux ne se déroulent pas directement en zone ATEX, des projections d'étincelles ou des scories peuvent atteindre une zone classée adjacente. La zone de sécurité de 10 m doit être respectée même en dehors de la zone ATEX délimitée.",
        "Consignation des fluides avant intervention : en cas de maintenance nécessitant l'ouverture d'un équipement contenant un fluide inflammable, il faut procéder à la consignation du circuit (isolement, dépressurisation, purge, verrouillage) selon la procédure décrite dans l'INRS ED 6109. Tant que la consignation n'est pas effective, la zone ATEX persiste.",
      ],
      keyPoints: [
        "Autorisation de travail = document obligatoire avant toute intervention en zone ATEX.",
        "Permis de feu = AT spécifique aux travaux générant des points chauds (soudage, meulage, perçage...).",
        "Zone de sécurité 10 m pour les travaux par points chauds — même hors zone ATEX délimitée.",
        "Mesure explosimètre obligatoire avant et pendant les travaux (seuil : < 20 % LIE).",
        "Signaler toute anomalie détectée au responsable sécurité AVANT de continuer les travaux.",
      ],
      legalRefs: [
        "Code du travail - Art. R.4515-8 : protocole de sécurité pour les opérations d'entreprises extérieures.",
        "Arrêté du 8 juillet 2003 - Art. 11 : mesures organisationnelles de prévention.",
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 4 : travaux et entreprises extérieures.",
        "INRS ED 6109 : consignation des énergies et des fluides.",
      ],
      resourceVideos: [
        {
          title: "Prévention du risque d'explosion ATEX — Mesures organisationnelles et DRPCE",
          description:
            "Vidéo INRS sur la démarche de prévention du risque explosion : rédaction du DRPCE, mesures de prévention (combustibles, sources d'inflammation), permis de feu et formation des salariés.",
          url: "https://youtu.be/1A6lYzE29Qo?si=DQY9BsHMQHJUi3pC",
          provider: "INRS / YouTube",
          ctaLabel: "Voir la vidéo — DRPCE et prévention",
        },
      ],
    },
    {
      id: "drpce-prevention",
      title: "4bis. Le DRPCE et les mesures de prévention",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-chantier-inrs.png",
      chapterImageAlt: "Chantier interdit au public — travaux de dégazage en zone ATEX — crédit photo INRS",
      intro:
        "Le Document Relatif à la Protection Contre les Explosions (DRPCE) est la pièce maîtresse de la prévention ATEX. Sa rédaction, sa mise à jour et son application concrète sont des obligations réglementaires de l'employeur.",
      content: [
        "Le DRPCE intègre l'ensemble de la démarche de prévention : analyse préliminaire des risques, évaluation, plan d'actions. Il est intégré au Document Unique d'Évaluation des Risques Professionnels (DUERP) et doit être actualisé annuellement, ou lors de tout changement (produits, procédés, organisation). Il est rédigé sous la responsabilité de l'employeur et soumis pour avis au CSE.",
        "Le DRPCE doit obligatoirement contenir : les risques d'explosion identifiés et évalués, les mesures prises ou à prendre et leur calendrier de mise en œuvre, la validation et le suivi de ces mesures, les emplacements classés en zones avec leurs volumes, les procédures à appliquer avant exécution des travaux, et le contenu des formations dispensées aux salariés exposés.",
        "Empêcher la formation d'une ATEX — agir sur les combustibles : remplacer le produit par un incombustible ou moins combustible, augmenter la granulométrie (passer de la poudre aux granulés), ajouter des solides inertes à des poussières combustibles, maîtriser les paramètres du procédé (température, pression), maintenir la concentration hors du domaine d'explosivité par captage à la source, dilution ou nettoyage régulier.",
        "Agir sur le comburant : introduire un gaz inerte (azote, argon) en proportions suffisantes pour appauvrir l'atmosphère en oxygène et rendre l'inflammation impossible. Attention au risque d'hypoxie pour tout salarié présent dans la zone concernée.",
        "Éviter les sources d'inflammation : mettre hors zone ATEX tout matériel qui n'a pas nécessité de s'y trouver. Éliminer flammes et feux nus, surfaces chaudes, étincelles mécaniques/électriques/électrostatiques, frottements mécaniques. Mettre en place des séparateurs magnétiques et gravitaires, des systèmes de refroidissement, et des détecteurs d'élévation de température et de pression.",
        "Limiter les effets d'une explosion si la formation d'une ATEX n'a pu être évitée : évents d'explosion, extincteurs déclenchés (suppresseurs), appareils résistant à la surpression, systèmes de découplage (arrête-flammes, écluses rotatives, vannes à fermeture rapide, déviateurs d'explosion). Ces systèmes sont eux-mêmes certifiés ATEX et doivent figurer dans le DRPCE.",
      ],
      deepDive: [
        "Mesures organisationnelles clés : modes opératoires d'exécution des tâches, permis de feu pour tous les travaux par points chauds, autorisation de travail pour toute opération en zone ATEX, limitation du nombre de travailleurs en zone, gestion de la coactivité avec les entreprises extérieures (plan de prévention, référent dédié), création de zones fumeurs à l'écart des zones ATEX.",
        "Contrôles et détection : détecteurs d'élévation de température et de pression, thermographie infrarouge pour les réseaux électriques (détection des points chauds), détecteurs de monoxyde de carbone (début de fermentation), contrôles de vitesse des bandes transporteuses (prévention des échauffements et des charges électrostatiques).",
        "Formation réglementaire (Code du travail) : le personnel travaillant en zone ATEX ou à proximité doit recevoir une formation sur le phénomène, les conditions de formation, les composantes et la prévention. Le personnel encadrant ou décisionnaire reçoit une formation spécifique sur les enjeux et les conséquences des choix d'équipements. Le personnel intervenant sur des appareils ATEX suit une formation adaptée aux modes de protection. La personne référente ATEX suit une formation complète.",
      ],
      keyPoints: [
        "DRPCE = intégré au DUERP — actualisé annuellement et à chaque changement significatif.",
        "Contenu obligatoire : risques identifiés, mesures, suivi, plans de zonage, procédures, formations.",
        "Prévention primaire : agir sur les combustibles, le comburant, les sources d'inflammation.",
        "Protection : évents, suppresseurs d'explosion, systèmes de découplage — tous certifiés ATEX.",
        "Formation du personnel = obligation légale pour toute personne travaillant en zone ATEX.",
      ],
      legalRefs: [
        "Code du travail - Art. R.4227-52 : contenu et mise à jour du DRPCE.",
        "Code du travail - Art. R.4227-50 : classement des emplacements en zones.",
        "Arrêté du 8 juillet 2003 : liste des mesures organisationnelles obligatoires.",
        "INRS ED 6030 : permis de feu — conception et mise en œuvre.",
        "INRS NT 33 : vêtements de travail antistatiques en zone ATEX.",
      ],
    },
    {
      id: "explosimetre-detection",
      title: "5. L'explosimètre — Utilisation, étalonnage et interprétation",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-marquage-ex-gaz.png",
      chapterImageAlt: "Explosimètre certifié Ex — lecture en % LIE et seuil d'alarme à 20%",
      visual: {
        title: "Explosimètre certifié Ex",
        subtitle: "Simulation : montée vers 20 % LIE → déclenchement alarme. Arrêt immédiat des travaux.",
        tone: "red" as const,
        animationKey: "atex-explosimetre" as const,
      },
      intro:
        "L'explosimètre est l'outil de détection indispensable avant toute intervention en zone ATEX. Un mauvais étalonnage ou une mauvaise utilisation peut donner une fausse sécurité aux conséquences mortelles.",
      content: [
        "L'explosimètre (ou détecteur de gaz combustibles) mesure la concentration de gaz dans l'air en pourcentage de la LIE. Le seuil d'alerte préconisé est de 20 % de la LIE (circulaire du 9 mai 1985). En dessous de ce seuil, le risque est considéré comme maîtrisé. Au-dessus, les travaux doivent être interrompus immédiatement.",
        "Problème critique d'étalonnage (source INERIS Omega 36) : un explosimètre étalonné au propane utilisé dans une atmosphère de méthane peut donner des lectures faussées. Exemple : lire 10 % sur un appareil étalonné au propane peut correspondre à une concentration réelle de 50 % dans du méthane — l'opérateur est EN DANGER alors qu'il croit être en sécurité. Inversement, un explosimètre étalonné au méthane utilisé dans du méthanol peut surestimer le danger.",
        "L'étalonnage doit être réalisé avec le gaz présent sur le site (ou un gaz étalon identique). L'INRS (document ED 116) préconise de spécifier le gaz étalon utilisé, les seuils d'alerte choisis et les corrections à appliquer selon les atmosphères potentiellement rencontrées.",
        "Contrôles avant utilisation : vérifier la date de la dernière vérification périodique (généralement 6 mois à 1 an selon fabricant), tester l'appareil avec un gaz de référence avant utilisation, s'assurer que la batterie est suffisamment chargée, et vérifier que la tête de détection n'est pas obstruée.",
        "Utilisation pratique : mesurer l'atmosphère dans les points bas (gaz plus lourds que l'air : hydrocarbures, LPG) ET dans les points hauts (gaz plus légers que l'air : hydrogène, méthane). En espace confiné, mesurer à plusieurs niveaux. Surveiller en continu pendant les travaux et déclencher l'évacuation dès l'alarme de premier seuil.",
      ],
      deepDive: [
        "Les détecteurs de gaz à point catalytique (catharométrie) sont les plus courants mais ne fonctionnent pas correctement en atmosphère appauvrie en oxygène (moins de 10 % d'O₂). Dans ce cas, utiliser un détecteur à technologie infrarouge ou photoionisation (PID). Cette limitation est critique en espace confiné.",
        "Pour les poussières, il n'existe pas d'équivalent portable de l'explosimètre. La prévention repose sur la suppression des sources d'inflammation, la ventilation et le nettoyage régulier des dépôts. En présence de poussières, la surveillance visuelle (nuage visible = danger) et le respect des procédures sont les seuls outils disponibles sur le terrain.",
        "Déport de mesure : en zone confinée ou difficile d'accès, utiliser un tube de prélèvement (sonde télescopique). Ne jamais pénétrer dans un espace confiné potentiellement ATEX sans mesure préalable depuis l'extérieur et sans équipier observateur à l'entrée.",
      ],
      keyPoints: [
        "Seuil d'alerte explosimètre = 20 % de la LIE. Au-dessus : arrêt immédiat des travaux.",
        "Étalonnage CRITIQUE : un explosimètre étalonné au mauvais gaz peut indiquer une fausse sécurité.",
        "Toujours vérifier : date de vérification périodique, batterie, test avec gaz de référence.",
        "Mesurer en points bas (gaz lourds) ET en points hauts (gaz légers) et en continu pendant les travaux.",
        "Détecteur catalytique inefficace en atmosphère appauvrie en O₂ — utiliser IR ou PID.",
      ],
      legalRefs: [
        "Circulaire du 9 mai 1985 : seuil d'alerte à 20 % de la LIE pour les détecteurs de gaz.",
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 4.3 : détection de la LIE.",
        "INRS ED 116 : choix et utilisation des détecteurs de gaz et vapeurs inflammables.",
        "Norme EN 60079-29-1 : exigences pour les détecteurs de gaz inflammables.",
      ],
    },
    {
      id: "epi-antistatiques",
      title: "6. EPI antistatiques — Sélection, port et entretien",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-fiche-epi-mabeo.png",
      chapterImageAlt: "Fiche EPI ATEX complète (Mabéo Industries) : casque EN 397/A1, combinaison EN 1149 + EN ISO 14116 + EN ISO 11612, gants EN 60903, chaussures EN ISO 20345",
      intro:
        "En zone ATEX, les EPI ont une double fonction : protéger l'intervenant et éviter d'être une source d'inflammation. Les décharges électrostatiques générées par des vêtements ou équipements ordinaires peuvent suffire à déclencher une explosion. Chaque EPI doit répondre à des normes précises vérifiables sur l'équipement.",
      content: [
        "L'électricité statique est l'une des principales sources d'inflammation en zone ATEX. Elle peut être générée par le frottement de vêtements synthétiques, la circulation de fluides dans des tuyaux, le déplacement de personnes sur un sol non antistatique, ou l'utilisation d'outils ou contenants non mis à la terre.",
        "Casque de protection : norme EN 397/A1 avec propriété ESD (antistatique). Les casques doivent dissiper les charges électrostatiques. Les casques en plastique non conducteur standard sont interdits en zone ATEX.",
        "Vêtements de travail : les vêtements portés en zone ATEX doivent répondre à 3 normes cumulatives : EN 1149-5 (dissipation électrostatique — résistance superficielle < 2,5 × 10^9 Ω), EN ISO 14116 (comportement à flamme limitée) et EN ISO 11612 (protection contre la chaleur et les flammes). Ils sont fabriqués à partir de fibres conductrices. Interdiction formelle de porter des vêtements synthétiques non antistatiques (polyester, nylon) sous ou à la place du vêtement certifié.",
        "Gants isolants : norme EN 60903 pour les travaux en présence de risques électriques en zone ATEX. Vérifier avant chaque utilisation l'absence de trou, de coupure ou de déformation. Pour les manipulations chimiques, utiliser des gants antistatiques adaptés aux produits présents — les gants en latex ou en nitrile synthétique peuvent accumuler des charges.",
        "Chaussures de sécurité antistatiques : conformes à la norme EN ISO 20345 avec propriétés ESD (Electrostatic Discharge). La résistance électrique doit être comprise entre 100 kΩ et 1000 MΩ pour dissiper les charges sans constituer un risque de choc électrique. Efficacité conditionnée à l'utilisation sur un sol conducteur ou semi-conducteur.",
        "Entretien des EPI antistatiques : laver les vêtements selon les instructions fabricant (certains détergents altèrent les propriétés antistatiques). Vérifier après chaque lavage que les propriétés sont conformes. Un vêtement endommagé (déchirure, réparation avec fil synthétique) perd ses propriétés — ne plus utiliser en zone ATEX. Durée de vie limitée : respecter les dates de péremption.",
      ],
      deepDive: [
        "Mise à la terre des équipements : tout équipement conducteur utilisé en zone ATEX (contenants, outils, équipements mobiles) doit être mis à la terre ou lié équipotentiellement au circuit pour éviter l'accumulation de charges électrostatiques. Cette liaison doit être vérifiée avant chaque utilisation.",
        "Détecteur de gaz certifié Ex : le détecteur personnel de gaz porté en zone ATEX doit lui-même être certifié Ex pour la zone concernée. Un détecteur non certifié peut constituer une source d'inflammation. Vérifier le marquage Ex sur l'appareil.",
        "Outils antistatiques : en zone 0 et zone 1, utiliser des outils en matériaux non générateurs d'étincelles (alliages bronze-aluminium, outils en plastique certifiés). En zone 2, les outils métalliques ordinaires sont généralement autorisés mais avec précaution (pas de chocs violent).",
      ],
      keyPoints: [
        "Vêtements EN 1149-5 obligatoires en zone ATEX — JAMAIS de vêtements synthétiques non certifiés.",
        "Chaussures ESD : résistance 100 kΩ à 1 GΩ — sol conducteur nécessaire pour l'efficacité.",
        "Vérifier l'état des EPI après chaque lavage — les propriétés antistatiques peuvent se dégrader.",
        "Tout équipement conducteur mobile doit être mis à la terre avant utilisation en zone ATEX.",
        "Le détecteur de gaz portatif lui-même doit être certifié Ex pour la zone concernée.",
      ],
      legalRefs: [
        "Code du travail - Art. R.4321-4 : obligation de l'employeur de fournir des EPI adaptés.",
        "Arrêté du 8 juillet 2003 - Art. 7 : mesures de protection contre les sources d'inflammation électrostatiques.",
        "Norme EN 1149-5 : vêtements de protection antistatiques.",
        "Norme EN ISO 20345 + EN 61340-4-3 : chaussures de sécurité antistatiques.",
      ],
    },
    {
      id: "outils-outillage-zone-atex",
      title: "7. Outils et outillage en zone ATEX",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-prevention-3axes.svg",
      chapterImageAlt: "Les 3 axes de prévention ATEX : agir sur le combustible, l'inflammation, l'organisation",
      intro:
        "Le choix des outils apportés en zone ATEX est aussi critique que le choix des équipements fixes. Un outil inadapté peut provoquer une étincelle mécanique ou électrique fatale.",
      content: [
        "Outils manuels : en zone 0 et zone 1, utiliser exclusivement des outils en matériaux non ferreux anti-étincelles (alliages cuivre-béryllium, bronze-aluminium). Ces outils sont marqués 'non incendiaires' ou 'ATEX' par le fabricant. En zone 2, les outils en acier ordinaire sont généralement autorisés sous réserve que le zonage soit confirmé et qu'il n'y ait pas de risque de choc.",
        "Outillage électrique et électronique : tout équipement électrique apporté en zone ATEX doit être certifié Ex pour la catégorie de zone. Cela inclut les lampes torches, les appareils de mesure (multimètres, pinces ampèremétriques), les perceuses, les radios et talkies-walkies, les téléphones portables, les ordinateurs portables.",
        "Véhicules et engins de manutention : les chariots élévateurs, engins de chantier et véhicules ne doivent pas pénétrer en zone ATEX sauf s'ils sont certifiés Ex pour la zone concernée. Les moteurs thermiques constituent une source d'inflammation multiple (étincelles d'allumage, surfaces chaudes, pot d'échappement).",
        "Éclairage de chantier : utiliser exclusivement des luminaires certifiés Ex. Les lampes à incandescence ordinaires (ampoules chaudes), les projecteurs halogènes et les lampes fluorescentes non certifiées sont interdits en zone classée.",
        "Appareils photos et caméras : les appareils photo et caméras ordinaires sont INTERDITS en zone ATEX (flash électrique, batterie non certifiée). Utiliser des appareils certifiés ATEX ou placer la zone hors ATEX avant toute prise de vue.",
      ],
      keyPoints: [
        "Zone 0 et 1 : outils anti-étincelles exclusivement (alliages cuivre-béryllium ou bronze-aluminium).",
        "Tout équipement électrique apporté en zone ATEX = certifié Ex obligatoire (même les lampes torches).",
        "Véhicules et engins : interdits en zone ATEX sauf certification Ex spécifique.",
        "Appareils photos/caméras ordinaires INTERDITS en zone ATEX.",
        "En cas de doute sur la certification d'un outil : ne pas l'utiliser, demander au responsable.",
      ],
      legalRefs: [
        "Arrêté du 8 juillet 2003 - Art. 11 : choix et utilisation des équipements de travail en zone ATEX.",
        "Code du travail - Art. L.4311-2 : définition des équipements de travail.",
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 5 : appareils ATEX.",
      ],
    },
    {
      id: "maintenance-verification-equipements",
      title: "8. Maintenance et vérification des équipements Ex",
      estimatedMinutes: 25,
      chapterImagePath: "/elearning/atex/atex-processus-accident.svg",
      chapterImageAlt: "Processus menant à l'accident ATEX — chaîne de défaillances et points de rupture",
      intro:
        "La maintenance des équipements Ex est réglementée et spécifique. Un équipement Ex mal entretenu ou réparé sans les précautions nécessaires perd sa certification et peut devenir une source d'inflammation.",
      content: [
        "La maintenance des matériels ATEX doit être effectuée par du personnel formé et qualifié. Toute intervention sur un équipement Ex doit être réalisée conformément à la notice du fabricant. Les pièces de remplacement doivent être des pièces d'origine ou équivalentes certifiées pour le même mode de protection.",
        "Lors d'une intervention de maintenance EN zone ATEX (1ère situation INERIS) : analyser le risque, mettre en œuvre en priorité des mesures de consignation des fluides pour supprimer l'ATEX ou réduire sa probabilité. Si la zone ATEX persiste malgré la consignation, elle doit être identifiée et faire l'objet de mesures spécifiques (zonage en phase maintenance).",
        "Lors d'une intervention de maintenance GÉNÉRANT une zone ATEX (2ème situation INERIS) : surveiller l'atmosphère en continu avec des détecteurs portables. L'absence d'ATEX doit être maintenue durant toute la durée des travaux et pendant une période supplémentaire après (temps de refroidissement, purge). Mesure de la LIE par détecteur continu.",
        "Lors d'interventions SUR des sources d'inflammation (3ème situation INERIS) : ouverture d'équipements électriques, travaux par points chauds. Ces opérations doivent être réalisées avec un permis de feu, la zone ATEX supprimée au préalable, et une surveillance continue de l'atmosphère.",
        "Vérifications périodiques des équipements Ex : selon la norme EN 60079-17, les équipements doivent faire l'objet de vérifications initiales (avant mise en service), de routine (visuelles régulières), détaillées (périodiques, démontage partiel si nécessaire) et approfondies (complètes). La périodicité dépend de l'environnement et des recommandations du fabricant.",
      ],
      deepDive: [
        "Remplacement de joints d'étanchéité sur un équipement Ex d (enveloppe antidéflagrante) : les joints doivent être remplacés par des joints identiques aux originaux (même matériau, mêmes dimensions, même référence). Un joint de dimensions différentes altère les jeux d'étanchéité qui définissent le mode de protection. L'équipement perd alors son niveau de protection certifié.",
        "Peinture sur équipement Ex : l'application d'une couche de peinture trop épaisse sur un équipement Ex peut modifier sa température maximale de surface (la peinture isole thermiquement) et le faire sortir de sa classe de température. Vérifier les recommandations du fabricant avant toute opération de peinture.",
        "Retour en zone après maintenance : avant de remettre un équipement Ex en service après maintenance, vérifier visuellement l'intégrité du mode de protection (absence de fissure, serrage des boulons d'assemblage, présence de tous les composants) et s'assurer que la documentation de maintenance a été mise à jour dans le DRPCE.",
      ],
      keyPoints: [
        "Maintenance Ex = personnel qualifié + pièces d'origine certifiées uniquement.",
        "3 situations INERIS : maintenance EN zone, maintenance GÉNÉRANT une zone, travaux SUR sources d'inflammation.",
        "Consignation des fluides EN PRIORITÉ avant toute intervention de maintenance en zone ATEX.",
        "Vérifications EN 60079-17 : initiales, de routine, détaillées, approfondies.",
        "Après maintenance : vérification visuelle du mode de protection avant remise en service.",
      ],
      legalRefs: [
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 4.4 : interventions de maintenance.",
        "Norme EN 60079-17 : vérification et maintenance des installations électriques en zone ATEX.",
        "INRS ED 6109 : consignation des énergies — mise en sécurité des machines.",
        "Arrêté du 8 juillet 2003 - Art. 11 : entretien des équipements en zone ATEX.",
      ],
    },
    {
      id: "conduite-urgence-signalement",
      title: "9. Conduite à tenir en cas d'anomalie ou d'incident",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-synthese-reflexes.svg",
      chapterImageAlt: "Les réflexes ATEX en cas d'anomalie ou d'incident — PEAS et procédure d'urgence",
      intro:
        "Face à une anomalie (odeur suspecte, alarme explosimètre, fuite visible) ou un incident, la réaction de l'intervenant dans les premières secondes est déterminante. Connaître la procédure et ne pas improviser.",
      content: [
        "En cas d'alarme de l'explosimètre (dépassement de 20 % de la LIE) : (1) STOPPER immédiatement les travaux. (2) Mettre hors tension les équipements électriques non Ex (ne pas déclencher de disjoncteur si possible — risque d'étincelle). (3) ÉVACUER la zone en remontant contre le vent. (4) ALERTER le PC de sécurité ou le responsable sécurité du site. (5) Ne pas réintégrer la zone sans autorisation et nouvelle vérification explosimètre.",
        "En cas de fuite de gaz ou vapeur inflammable visible ou olfactive : même procédure que l'alarme explosimètre. Ne pas utiliser de téléphone portable ordinaire (non certifié Ex) dans la zone. Attendre en dehors de la zone les instructions du responsable sécurité.",
        "En cas d'incendie en zone ATEX : si le feu est petit et ne menace pas de s'étendre à une zone de stockage de matières inflammables, attaquer avec un extincteur adapté (CO₂ pour les zones à risque ATEX — pas d'eau en présence de gaz inflammable). Si le feu implique une zone ATEX ou un équipement sous pression : évacuer immédiatement et appeler les secours (18 ou 112).",
        "Réflexe PEAS en cas d'accident avec victime : Protéger (supprimer le danger si possible — couper l'alimentation gaz, ventiler), Examiner (état de la victime sans la déplacer si suspicion de fracture), Alerter (18 SAMU, 18 pompiers ou 112 — préciser qu'il s'agit d'une zone ATEX), Secourir (premiers gestes de secourisme en attendant les secours).",
        "Signalement des anomalies : toute anomalie constatée en zone ATEX (équipement défaillant, fuite, dépôt de poussières anormal, détecteur de gaz en défaut) doit être signalée IMMÉDIATEMENT au responsable sécurité et consignée dans le registre prévu à cet effet. Ne jamais laisser une anomalie non signalée.",
      ],
      keyPoints: [
        "Alarme explosimètre → Stopper → Évacuer (vent dans le dos) → Alerter → Attendre hors zone.",
        "NE PAS utiliser de téléphone portable non certifié Ex pour alerter depuis la zone.",
        "Incendie ATEX : CO₂ si feu maîtrisable, ÉVACUER et appeler 18/112 si non maîtrisable.",
        "PEAS : Protéger, Examiner, Alerter, Secourir — préciser 'zone ATEX' aux secours.",
        "Toute anomalie = signalement immédiat et consignation dans le registre. Pas de 'bricolage' sur site.",
      ],
      legalRefs: [
        "Code du travail - Art. L.4131-1 : droit de retrait du salarié face au danger grave et imminent.",
        "Code du travail - Art. R.4227-49 : formation des travailleurs à la conduite à tenir en cas d'explosion.",
        "Arrêté du 8 juillet 2003 - Art. 9 : consignes de sécurité et signalement des anomalies.",
      ],
    },
    {
      id: "electricite-installations-ex",
      title: "10. Spécificités électriques — Câblage, armoires Ex et instrumentation",
      estimatedMinutes: 30,
      chapterImagePath: "/elearning/atex/atex-marquage-categories.svg",
      chapterImageAlt: "Câblage, presses-étoupe Ex et armoires électriques en zone ATEX",
      intro:
        "En zone ATEX, deux grandes familles de sources d'inflammation doivent être maîtrisées : les sources électriques (arcs, étincelles, échauffements de composants) et les sources mécaniques (friction, choc, charges électrostatiques). Ce chapitre traite exclusivement de l'ATEX électrique — le domaine le plus contraignant, car l'électricité génère naturellement des étincelles et des arcs. Les méthodes de protection sont normalisées (Ex d, Ex e, Ex i…), la certification est systématiquement réalisée par un organisme notifié, et les classes de température (T1 à T6) sont contrôlées strictement. Ce chapitre est destiné aux électriciens, instrumentistes et techniciens de maintenance électrique intervenant sur des installations en zone ATEX. Il complète les fondamentaux par les exigences spécifiques au câblage Ex, aux armoires et à l'instrumentation en sécurité intrinsèque. Les exigences mécaniques (friction, pompes, roulements) sont traitées dans le chapitre suivant.",
      content: [
        "Câbles et presse-étoupe certifiés Ex : le câble lui-même ne porte pas de certification ATEX, mais doit être sélectionné selon des critères stricts — gaine résistante aux produits chimiques présents, tenue mécanique adaptée à l'environnement, section calculée pour éviter tout échauffement anormal. La traversée des parois de boîtiers Ex se fait obligatoirement avec des presse-étoupe certifiés Ex. Pour un boîtier Ex d (antidéflagrant), le presse-étoupe doit lui-même être certifié Ex d selon EN 60079-1 Annexe A. Un presse-étoupe standard annule intégralement le niveau de protection du boîtier. De même, un orifice de câble non occupé doit être obturé avec un bouchon certifié Ex — ne jamais laisser un trou ouvert dans un boîtier Ex.",
        "Armoires électriques Ex à surpression interne (Ex p) : ces armoires maintiennent à l'intérieur une pression positive d'air propre ou de gaz inerte pour empêcher l'atmosphère explosive d'y pénétrer. Protocole impératif avant toute ouverture : (1) couper l'alimentation électrique ; (2) arrêter le circuit de pressurisation ; (3) attendre la durée de purge définie par le fabricant (généralement 5 à 15 minutes selon le volume de l'armoire) ; (4) vérifier l'équilibrage de pression avant d'ouvrir. NE JAMAIS ouvrir une armoire Ex p sous tension et sous pression en zone ATEX — risque d'étincelle d'ouverture en atmosphère explosive.",
        "Instrumentation en sécurité intrinsèque (Ex ia / Ex ib) : les capteurs en zone 0 et zone 1 (pression, niveau, température, débit) sont souvent protégés par sécurité intrinsèque. Le principe : des barrières Zener ou des séparateurs galvaniques placés en armoire hors zone limitent l'énergie électrique disponible au niveau du capteur à une valeur inférieure à l'énergie minimale d'inflammation du gaz présent. Points critiques : (1) ne jamais brancher un circuit Ex ia à un circuit non-intrinsèquement sûr — toute injection d'énergie extérieure détruit la protection et peut provoquer une étincelle ; (2) respecter la résistance maximale de boucle spécifiée par le fabricant ; (3) utiliser exclusivement des câbles de boucle IS (Intrinsically Safe) — généralement gaine bleue — pour les circuits en zone 0 et 1.",
        "Inspection des installations électriques Ex — norme EN 60079-17 : la norme distingue 3 niveaux. (1) Inspection visuelle : contrôle externe sans démontage — intégrité du boîtier, absence de corrosion, de fissures, de dégradation mécanique, visserie de fermeture complète, étiquetage présent. (2) Inspection rapprochée : ouverture du boîtier pour contrôler l'état des connexions, la propreté, les composants accessibles, les sections de câbles, l'absence de condensation anormale. (3) Inspection détaillée : démontage complet selon les instructions du fabricant, vérification de chaque composant et du mode de protection (jeux d'assemblage, état des joints, serrage des brides). La périodicité est définie par l'employeur selon l'environnement — en atmosphère corrosive ou fortement vibrante, les intervalles sont raccourcis par rapport aux valeurs indicatives du fabricant.",
        "Moteurs électriques Ex — surveillance et anomalies : signes de défaillance critiques à surveiller lors des rondes et maintenances. (1) Vibration anormale : souvent liée à un roulement dégradé ou à un déséquilibre du rotor — un moteur qui vibre peut atteindre une température de surface supérieure à sa classe de température T et constituer une source d'inflammation directe. (2) Surchauffe : un disjoncteur qui déclenche répétitivement sur surcharge thermique est un signal d'alarme — vérifier la ventilation, l'encrassement du filtre, la compatibilité de la puissance avec la charge. (3) Bruit anormal : craquement (roulement), sifflement (déséquilibre aérodynamique). (4) Traces d'huile sur le boîtier (fuite de palier). Toute anomalie = arrêt immédiat du moteur et signalement au responsable sécurité avant toute remise en service.",
      ],
      deepDive: [
        "Luminaires Ex : les luminaires en zone ATEX doivent être certifiés Ex pour la catégorie de zone. Les LED Ex ont remplacé les lampes à incandescence et les fluorescents compacts (risque de bris de tube libérant du mercure). Pour les zones à poussières (20 et 21), les luminaires doivent avoir une surface lisse et continue pour éviter les accumulations de dépôts — une couche de poussières sur la surface chaude d'un luminaire constitue une source d'inflammation directe. Vérifier la température maximale de surface du luminaire (classe T) par rapport à la MIT (Minimum Ignition Temperature) des poussières présentes.",
        "Modifications des installations électriques Ex : toute modification (ajout d'un capteur, changement de câble, ajout d'un départ en armoire) doit être précédée d'une analyse d'impact sur le mode de protection existant. La modification doit être documentée dans le DRPCE et tracée dans le registre de maintenance Ex. Cas fréquent de non-conformité : percer un trou supplémentaire dans un boîtier Ex d sans utiliser de presse-étoupe certifié adapté, ou remplacer un composant par un équivalent non certifié Ex.",
        "Continuité de l'équipotentialité : en zone ATEX, la mise à la terre et la continuité de l'équipotentialité de toutes les masses conductrices (structures métalliques, tuyauteries, équipements) sont critiques pour l'évacuation des charges électrostatiques. Vérification à l'ohmmètre : résistance de continuité < 1 Ω entre deux points de l'installation. Les connexions oxydées ou lâches augmentent la résistance et réduisent l'efficacité de l'écoulement des charges. Les liaisons équipotentielles doivent être vérifiées lors des inspections détaillées.",
      ],
      keyPoints: [
        "Presse-étoupe : certification Ex obligatoire — un presse-étoupe standard ou un trou non bouché annule la protection du boîtier.",
        "Armoire Ex p : alimentation coupée + purge complète avant ouverture — jamais ouvrir sous tension en zone ATEX.",
        "Circuit Ex ia : ne jamais connecter à un circuit non-intrinsèquement sûr — énergie extérieure = protection annulée.",
        "EN 60079-17 : 3 niveaux d'inspection — visuelle, rapprochée, détaillée — périodicité définie par l'employeur.",
        "Moteur Ex : vibration, surchauffe ou bruit anormal = arrêt immédiat + signalement avant toute remise en service.",
      ],
      legalRefs: [
        "Norme EN 60079-17 : inspection et entretien des installations électriques en atmosphères explosives.",
        "Norme EN 60079-14 : conception et construction des installations électriques en atmosphères explosives.",
        "Norme EN 60079-11 : sécurité intrinsèque (Ex ia, Ex ib) — exigences matériels et boucles.",
        "Directive 2014/34/UE : exigences essentielles pour les appareils et systèmes de protection ATEX.",
      ],
    },
    {
      id: "equipements-mecaniques-ex",
      title: "11. Spécificités mécaniques — Pompes, joints et équipements non électriques",
      estimatedMinutes: 30,
      chapterImagePath: "/elearning/atex/atex-prevention-3axes.svg",
      chapterImageAlt: "Équipements mécaniques non électriques en zone ATEX — pompes, compresseurs, joints",
      intro:
        "Là où l'ATEX électrique (chapitre précédent) vise à empêcher arcs et étincelles électriques, l'ATEX mécanique vise à empêcher qu'un mécanisme en mouvement ne devienne lui-même une source d'inflammation — par friction, choc, échauffement ou accumulation électrostatique. Les exigences diffèrent fondamentalement : pas de méthodes Ex d/e/i ici, mais un contrôle des matériaux, de la conception et des limites de température de surface. La certification est parfois possible par auto-évaluation pour certains équipements non électriques en Zone 2, ce qui n'existe pas pour le domaine électrique. Ce chapitre est destiné aux mécaniciens, monteurs, chaudronniers et techniciens de maintenance mécanique. Ces risques mécaniques sont souvent sous-estimés sur le terrain par rapport aux risques électriques — à tort, car un roulement en fin de vie ou une garniture à sec peut provoquer un incendie aussi rapidement qu'une étincelle électrique.",
      content: [
        "Équipements mécaniques non électriques en zone ATEX : contrairement aux idées reçues, les équipements mécaniques non électriques (pompes, compresseurs, agitateurs, ventilateurs, réducteurs, convoyeurs) sont soumis à la directive 2014/34/UE et à la norme EN 13463 depuis le 30 juin 2003. Tout équipement non électrique présentant une source potentielle d'inflammation propre (friction, choc, surface chaude) doit être certifié Ex pour la zone où il est utilisé, à moins qu'une évaluation documentée démontre qu'il n'en présente aucune. Les équipements mis en service avant 2003 peuvent rester en service sous conditions de maintien documenté dans le DRPCE.",
        "Sources d'inflammation mécaniques — friction et choc : (1) Friction : un roulement dégradé, une garniture mécanique fonctionnant à sec, une courroie patinant sur une poulie peuvent générer une chaleur suffisante pour dépasser la TAI du produit inflammable présent dans la zone. La vitesse de rotation est un paramètre de risque majeur — un roulement chaud à 3 000 tr/min peut provoquer un incendie en quelques secondes. (2) Choc : fragment d'aubage d'un ventilateur touchant le carter, outil tombant sur une surface métallique, pièce mal serrée frottant sur le carter = étincelle mécanique susceptible d'atteindre plusieurs centaines de degrés.",
        "Pompes centrifuges et volumétriques en zone ATEX : les pompes pour liquides inflammables doivent être certifiées Ex. Risques spécifiques à maîtriser : (1) Cavitation — génère vibrations intenses et échauffement des paliers ; indicateur sonore caractéristique (claquements). (2) Fonctionnement à sec — la garniture mécanique perd sa lubrification, frotte à sec et surchauffe jusqu'à atteindre la TAI du produit. (3) Fuite de garniture — libération de vapeur ou liquide inflammable créant une zone ATEX locale non cartographiée. Vérifications avant intervention : pression d'aspiration suffisante, absence de fuite visible, niveau d'huile des paliers, température des paliers.",
        "Garnitures mécaniques et joints d'étanchéité — choix et surveillance : la garniture mécanique est le premier point de défaillance d'une pompe en zone ATEX. (1) Garniture simple : acceptable pour liquides peu volatils — fuit à terme. (2) Garniture double à fluide de barrage (pressurized barrier fluid) : le fluide de barrage est maintenu à une pression supérieure au produit pompé, garantissant l'étanchéité même en cas d'usure partielle de la garniture primaire. Recommandée pour les hydrocarbures volatils, solvants et produits à point éclair < 21 °C en zone 1. Le fluide de barrage doit être compatible avec le produit et renouvelé selon le programme de maintenance.",
        "Compresseurs et ventilateurs en zone ATEX : risques spécifiques. Compresseurs d'air lubrifiés : contamination du refoulement par de l'huile en suspension — risque d'ATEX dans le réseau aval si l'air comprimé est utilisé en zone. Compresseurs de gaz : fuite aux joints de piston ou de tige. Ventilateurs : risque de contact roue-carter en cas d'usure des paliers ou d'aspiration d'un corps étranger — les roues de ventilateurs ATEX sont en matériaux non générateurs d'étincelles par choc (alliages aluminium-bronze, revêtements non ferreux) ou avec jeu réduit garanti. Surveillance obligatoire lors des rondes : température des paliers (thermomètre ou caméra IR), niveau de vibrations, bruit anormal.",
      ],
      deepDive: [
        "Norme EN 13463 — modes de protection mécaniques : la norme EN 13463 (remplacée progressivement par EN ISO 80079-36 et 80079-37) définit les modes de protection pour équipements non électriques. Principaux modes : 'c' (sécurité de construction) — conception pour supprimer toute source d'inflammation en fonctionnement normal, le plus courant pour les pompes et réducteurs ; 'fr' (contrôle des sources d'inflammation par friction) — mesures spécifiques anti-friction (jeux garantis, matériaux non générateurs d'étincelles, surveillance de vitesse) ; 'b' (enveloppe antidéflagrante) — résistance à une explosion interne ; 'k' (immersion dans un liquide) — immersion des parties actives pour éliminer le contact avec l'atmosphère explosive.",
        "Roulements en zone ATEX — surveillance précoce : la défaillance de roulement est une des causes majeures d'accident mécanique en zone ATEX. Indicateurs précoces à surveiller : vibration anormale (mesurable par accéléromètre lors des rondes vibratoires), bruit (craquement sourd = début de détérioration de la piste, sifflement = défaut de graissage), élévation de température du palier (thermocouple de surveillance continue ou thermomètre à contact). Sur-graissage = surchauffe par agitation mécanique du lubrifiant. Sous-graissage = contact métal-métal = friction. En zone 0, les roulements magnétiques ou à palier hydrodynamique (sans contact mécanique) permettent de supprimer entièrement le risque de friction.",
        "Nettoyage mécanique en zone poussières : le nettoyage à l'air comprimé est INTERDIT en zone à risque de poussières combustibles — il remet les dépôts en suspension et crée instantanément une atmosphère explosive (zone 20 transitoire) dans un espace qui était en zone 22 au repos. Utiliser exclusivement des aspirateurs certifiés Ex pour la zone concernée, ou le nettoyage humide contrôlé. Pour les équipements huileux, le nettoyage avec solvants inflammables nécessite une Autorisation de Travail spécifique (zone ATEX créée temporairement). Le nettoyage des filtres à manches, dépoussiéreurs et silos doit être consigné dans le registre d'entretien et planifié hors production si possible.",
        "Synthèse comparative — ATEX électrique vs ATEX mécanique : les deux domaines relèvent de la même directive 2014/34/UE mais avec des logiques très différentes. ATEX électrique : sources = arcs, étincelles, échauffements de composants ; méthodes de protection normalisées Ex d / Ex e / Ex i / Ex p / Ex n ; certification toujours par organisme notifié pour cat. 1 et 2 ; complexité très élevée. ATEX mécanique : sources = friction, choc, électrostatique, surfaces chaudes ; méthodes de protection = choix des matériaux, conception (jeux garantis, dissipation électrostatique), limitation de température ; certification parfois par auto-évaluation (cat. 3 et équipements non électriques cat. 2) ; complexité moyenne. En pratique : un moteur électrique peut créer une étincelle interne → protection électrique obligatoire. Un ventilateur mécanique peut accumuler de l'électricité statique ou chauffer par friction → protection mécanique obligatoire. Les deux doivent être certifiés 2014/34/UE, mais les exigences diffèrent fortement selon la nature de l'équipement.",
      ],
      keyPoints: [
        "ATEX électrique vs mécanique : même directive (2014/34/UE), mais logiques opposées — élec = étincelles/arcs maîtrisés par modes Ex normalisés ; méca = friction/choc maîtrisés par matériaux et conception.",
        "Tout équipement mécanique non électrique avec source d'inflammation potentielle = certification Ex obligatoire depuis le 30 juin 2003.",
        "Friction et choc : roulement dégradé, garniture à sec, ventilateur vibrant = sources d'inflammation mécaniques réelles.",
        "Pompe en zone 1 avec hydrocarbures volatils : garniture double à fluide de barrage recommandée.",
        "Nettoyage air comprimé INTERDIT en zone poussières — aspirateur certifié Ex ou nettoyage humide uniquement.",
        "Roulement : vibration + surchauffe + bruit = arrêt immédiat. Sur/sous-graissage = risque d'incendie.",
      ],
      legalRefs: [
        "Norme EN 13463-1 (et EN ISO 80079-36) : équipements non électriques pour atmosphères explosives — règles générales.",
        "Norme EN 13463-5 (et EN ISO 80079-37) : protection par sécurité de construction 'c'.",
        "Directive 2014/34/UE : champ d'application incluant les équipements non électriques depuis 2003.",
        "Guide INERIS Omega 36 (octobre 2025) - Chapitre 5 : appareils et systèmes de protection non électriques.",
      ],
    },
    {
      id: "synthese-quiz-n1",
      title: "12. Synthèse et préparation à l'évaluation",
      estimatedMinutes: 20,
      chapterImagePath: "/elearning/atex/atex-bonnes-pratiques-inrs.png",
      chapterImageAlt: "INRS — Atmosphères explosives : les bonnes pratiques ATEX (affiche officielle de référence)",
      intro:
        "Ce chapitre final consolide les points essentiels du Niveau 1 et vous prépare au quiz de validation et à la classe virtuelle de 4 heures avec votre formateur PREVENSIA.",
      content: [
        "Les 10 règles de l'intervenant en zone ATEX : (1) Consulter le DRPCE et le plan de zonage avant toute intervention. (2) Obtenir l'autorisation de travail ou le permis de feu signé. (3) Vérifier et tester l'explosimètre (étalonnage, batterie, gaz de référence). (4) Mesurer l'atmosphère avant d'entrer (< 20 % LIE). (5) Porter les EPI antistatiques (vêtements EN 1149-5, chaussures ESD). (6) N'apporter que des équipements et outils certifiés Ex adaptés à la zone. (7) Mettre à la terre tous les équipements conducteurs mobiles. (8) Respecter la zone de sécurité de 10 m pour les travaux par points chauds. (9) Surveiller l'atmosphère en continu pendant les travaux. (10) Signaler toute anomalie immédiatement.",
        "L'avis d'habilitation ATEX Niveau 1 qui vous sera remis à l'issue de la classe virtuelle atteste que vous possédez les connaissances théoriques et pratiques nécessaires pour intervenir en zone ATEX de manière sécurisée. Il est valable 3 ans. L'employeur reste responsable de l'autorisation formelle d'intervenir en zone classée.",
        "La classe virtuelle de 4 heures avec votre formateur PREVENSIA portera sur : des cas pratiques de décodage de marquages Ex, des exercices sur les procédures d'autorisation de travail et permis de feu, des mises en situation selon votre domaine (électrique ou mécanique), la conduite à tenir en cas d'anomalie, et les particularités de votre site.",
      ],
      keyPoints: [
        "10 règles de l'intervenant — à mémoriser et appliquer systématiquement.",
        "Avis d'habilitation ATEX N1 = attestation théorique valable 3 ans. L'employeur autorise formellement.",
        "Classe virtuelle 4h : marquages Ex, procédures AT/permis feu, mises en situation élec/méca, spécificités site.",
        "Recyclage obligatoire tous les 3 ans pour maintenir l'habilitation.",
      ],
      legalRefs: [
        "Code du travail - Art. R.4227-49 : formation obligatoire des travailleurs exposés aux risques ATEX.",
        "Arrêté du 8 juillet 2003 : obligations générales de l'employeur.",
        "Directive 99/92/CE : prescriptions minimales visant à améliorer la protection des travailleurs.",
      ],
    },
  ],
  resourceFiles: [
    {
      title: "Livret Stagiaire ATEX Niveau 1",
      description:
        "Support de formation complet : 12 modules illustrés avec photos réelles (Mabéo, INERIS, INRS), normes EPI (EN 1149-5, EN ISO 14116, EN ISO 11612, EN 60903, EN ISO 20345), marquage Ex, DRPCE, PEAS et QCM de 15 questions. À conserver comme référence après la formation.",
      url: "/downloads/atex/ATEX_N1_Livret_Stagiaire.pdf",
      fileType: "pdf",
      ctaLabel: "Télécharger le livret (PDF)",
    },
  ],
};
