const MOJIBAKE_REPLACEMENTS: Array<[string, string]> = [
  ["\u00C3\u00A0", "\u00E0"],
  ["\u00C3\u00A2", "\u00E2"],
  ["\u00C3\u00A4", "\u00E4"],
  ["\u00C3\u00A7", "\u00E7"],
  ["\u00C3\u00A8", "\u00E8"],
  ["\u00C3\u00A9", "\u00E9"],
  ["\u00C3\u00AA", "\u00EA"],
  ["\u00C3\u00AB", "\u00EB"],
  ["\u00C3\u00AE", "\u00EE"],
  ["\u00C3\u00AF", "\u00EF"],
  ["\u00C3\u00B4", "\u00F4"],
  ["\u00C3\u00B6", "\u00F6"],
  ["\u00C3\u0153", "\u0153"],
  ["\u00C3\u00B9", "\u00F9"],
  ["\u00C3\u00BB", "\u00FB"],
  ["\u00C3\u00BC", "\u00FC"],
  ["\u00E2\u20AC\u2122", "\u2019"],
  ["\u00E2\u20AC\u0153", "\u201C"],
  ["\u00E2\u20AC?", "\u201D"],
  ["\u00E2\u20AC\u201D", "\u2014"],
  ["\u00E2\u20AC\u201C", "\u2013"],
  ["\u00E2\u20AC\u00A6", "\u2026"],
  ["\u00C2\u00A0", " "],
];

const FRENCH_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\badequation\b/gi, "ad\u00E9quation"],
  [/\banterieure\b/gi, "ant\u00E9rieure"],
  [/\bappeles\b/gi, "appel\u00E9s"],
  [/\bappuyee\b/gi, "appuy\u00E9e"],
  [/\barret\b/gi, "arr\u00EAt"],
  [/\battribue\b/gi, "attribu\u00E9"],
  [/\bautorisation\b/gi, "autorisation"],
  [/\bautorisations\b/gi, "autorisations"],
  [/\bchaine\b/gi, "cha\u00EEne"],
  [/\bclarte\b/gi, "clart\u00E9"],
  [/\bcoherence\b/gi, "coh\u00E9rence"],
  [/\bconfirmee\b/gi, "confirm\u00E9e"],
  [/\bconfirmees\b/gi, "confirm\u00E9es"],
  [/\bcomplete\b/gi, "compl\u00E8te"],
  [/\bcompleter\b/gi, "compl\u00E9ter"],
  [/\bcompletes\b/gi, "compl\u00E8tes"],
  [/\bconnexion\b/gi, "connexion"],
  [/\bconnaitre\b/gi, "conna\u00EEtre"],
  [/\bconnait\b/gi, "conna\u00EEt"],
  [/\bcoordination\b/gi, "coordination"],
  [/\bcoordonnee\b/gi, "coordonn\u00E9e"],
  [/\bcoordonnees\b/gi, "coordonn\u00E9es"],
  [/\bcoute\b/gi, "co\u00FBte"],
  [/\bdeja\b/gi, "d\u00E9j\u00E0"],
  [/\bdelimitation\b/gi, "d\u00E9limitation"],
  [/\bdelimiter\b/gi, "d\u00E9limiter"],
  [/\bdelivre\b/gi, "d\u00E9livre"],
  [/\bdelivrance\b/gi, "d\u00E9livrance"],
  [/\bdepannage\b/gi, "d\u00E9pannage"],
  [/\bdiplome\b/gi, "dipl\u00F4me"],
  [/\becarts\b/gi, "\u00E9carts"],
  [/\beclairage\b/gi, "\u00E9clairage"],
  [/\becrit\b/gi, "\u00E9crit"],
  [/\becrite\b/gi, "\u00E9crite"],
  [/\benergie\b/gi, "\u00E9nergie"],
  [/\benvironnement degrade\b/gi, "environnement d\u00E9grad\u00E9"],
  [/\betre\b/gi, "\u00EAtre"],
  [/\bevaluation\b/gi, "\u00E9valuation"],
  [/\bevaluations\b/gi, "\u00E9valuations"],
  [/\bexecutant\b/gi, "ex\u00E9cutant"],
  [/\bexecutants\b/gi, "ex\u00E9cutants"],
  [/\bexecute\b/gi, "ex\u00E9cute"],
  [/\bexecuter\b/gi, "ex\u00E9cuter"],
  [/\bexecution\b/gi, "ex\u00E9cution"],
  [/\bexperience\b/gi, "exp\u00E9rience"],
  [/\bexperimentee\b/gi, "exp\u00E9riment\u00E9e"],
  [/\bfiabilite\b/gi, "fiabilit\u00E9"],
  [/\bformalise\b/gi, "formalis\u00E9"],
  [/\bformalisee\b/gi, "formalis\u00E9e"],
  [/\bformalite\b/gi, "formalit\u00E9"],
  [/\bformees\b/gi, "form\u00E9es"],
  [/\bgenerale\b/gi, "g\u00E9n\u00E9rale"],
  [/\bgeometrie\b/gi, "g\u00E9om\u00E9trie"],
  [/\bguidee\b/gi, "guid\u00E9e"],
  [/\bhabilite\b/gi, "habilit\u00E9"],
  [/\bhabilitees\b/gi, "habilit\u00E9es"],
  [/\bidentifie\b/gi, "identifi\u00E9"],
  [/\bidentifiee\b/gi, "identifi\u00E9e"],
  [/\bimmediat\b/gi, "imm\u00E9diat"],
  [/\bimmediatement\b/gi, "imm\u00E9diatement"],
  [/\bindefinie\b/gi, "ind\u00E9finie"],
  [/\bjournee\b/gi, "journ\u00E9e"],
  [/\blevee\b/gi, "lev\u00E9e"],
  [/\bmaitrise\b/gi, "ma\u00EEtrise"],
  [/\bmaitrisee\b/gi, "ma\u00EEtris\u00E9e"],
  [/\bmaitriser\b/gi, "ma\u00EEtriser"],
  [/\bmateriel\b/gi, "mat\u00E9riel"],
  [/\bmateriels\b/gi, "mat\u00E9riels"],
  [/\bmecanique\b/gi, "m\u00E9canique"],
  [/\bmelanger\b/gi, "m\u00E9langer"],
  [/\bmeme\b/gi, "m\u00EAme"],
  [/\bmetier\b/gi, "m\u00E9tier"],
  [/\bmethode\b/gi, "m\u00E9thode"],
  [/\bmethodique\b/gi, "m\u00E9thodique"],
  [/\boperation\b/gi, "op\u00E9ration"],
  [/\boperationnelle\b/gi, "op\u00E9rationnelle"],
  [/\boperationnelles\b/gi, "op\u00E9rationnelles"],
  [/\boperations\b/gi, "op\u00E9rations"],
  [/\boperateur\b/gi, "op\u00E9rateur"],
  [/\boperateurs\b/gi, "op\u00E9rateurs"],
  [/\borganisee\b/gi, "organis\u00E9e"],
  [/\bperimetre\b/gi, "p\u00E9rim\u00E8tre"],
  [/\bpieces\b/gi, "pi\u00E8ces"],
  [/\bphotovoltaique\b/gi, "photovolta\u00EFque"],
  [/\bphotovoltaiques\b/gi, "photovolta\u00EFques"],
  [/\bprecises\b/gi, "pr\u00E9cises"],
  [/\bpreparation\b/gi, "pr\u00E9paration"],
  [/\bprepare\b/gi, "pr\u00E9pare"],
  [/\bpreparee\b/gi, "pr\u00E9par\u00E9e"],
  [/\bpreparer\b/gi, "pr\u00E9parer"],
  [/\bpresence\b/gi, "pr\u00E9sence"],
  [/\bprocede\b/gi, "proc\u00E9d\u00E9"],
  [/\bprotection degradee\b/gi, "protection d\u00E9grad\u00E9e"],
  [/\bqualite\b/gi, "qualit\u00E9"],
  [/\brealise\b/gi, "r\u00E9alise"],
  [/\brealisee\b/gi, "r\u00E9alis\u00E9e"],
  [/\brealiser\b/gi, "r\u00E9aliser"],
  [/\breel\b/gi, "r\u00E9el"],
  [/\breelle\b/gi, "r\u00E9elle"],
  [/\breelles\b/gi, "r\u00E9elles"],
  [/\breflexe\b/gi, "r\u00E9flexe"],
  [/\breflexes\b/gi, "r\u00E9flexes"],
  [/\breglementaire\b/gi, "r\u00E9glementaire"],
  [/\breglementaires\b/gi, "r\u00E9glementaires"],
  [/\breperage\b/gi, "rep\u00E9rage"],
  [/\brepresente\b/gi, "repr\u00E9sente"],
  [/\bresponsabilite\b/gi, "responsabilit\u00E9"],
  [/\bresponsabilites\b/gi, "responsabilit\u00E9s"],
  [/\bretour d'experience\b/gi, "retour d'exp\u00E9rience"],
  [/\brole\b/gi, "r\u00F4le"],
  [/\broles\b/gi, "r\u00F4les"],
  [/\bsalarie\b/gi, "salari\u00E9"],
  [/\bsalaries\b/gi, "salari\u00E9s"],
  [/\bschema\b/gi, "sch\u00E9ma"],
  [/\bsecurite\b/gi, "s\u00E9curit\u00E9"],
  [/\bsecurisee\b/gi, "s\u00E9curis\u00E9e"],
  [/\bsequence\b/gi, "s\u00E9quence"],
  [/\bsupplementaire\b/gi, "suppl\u00E9mentaire"],
  [/\bsure\b/gi, "s\u00FBre"],
  [/\bsynthese\b/gi, "synth\u00E8se"],
  [/\btaches\b/gi, "t\u00E2ches"],
  [/\btheorie\b/gi, "th\u00E9orie"],
  [/\btheorique\b/gi, "th\u00E9orique"],
  [/\btheoriques\b/gi, "th\u00E9oriques"],
  [/\btracabilite\b/gi, "tra\u00E7abilit\u00E9"],
  [/\bunicite\b/gi, "unicit\u00E9"],
  [/\bverifie\b/gi, "v\u00E9rifie"],
  [/\bverification\b/gi, "v\u00E9rification"],
  [/\bverifications\b/gi, "v\u00E9rifications"],
];

function applyCase(source: string, replacement: string) {
  if (source.toUpperCase() === source) {
    return replacement.toUpperCase();
  }

  if (source[0] && source[0] === source[0].toUpperCase()) {
    return replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }

  return replacement;
}

function repairMojibake(text: string) {
  return MOJIBAKE_REPLACEMENTS.reduce(
    (result, [source, replacement]) => result.split(source).join(replacement),
    text
  );
}

export function formatFrenchDisplayText(text: string | null | undefined) {
  if (!text) return "";

  const repaired = repairMojibake(text);

  return FRENCH_REPLACEMENTS.reduce(
    (result, [pattern, replacement]) =>
      result.replace(pattern, (match) => applyCase(match, replacement)),
    repaired
  );
}
